export const unicodeList = [
  { character: '&#128;', decimalCode: '&amp;#128;', name: 'Euro sign (&amp;euro; or &amp;#8364;)', characterSet: 'ANSI' },
  { character: '&#134;', decimalCode: '&amp;#134;', name: 'Dagger (&amp;dagger;)', characterSet: 'ANSI' },
  { character: '&#135;', decimalCode: '&amp;#135;', name: 'Double dagger (&amp;Dagger;)', characterSet: 'ANSI' },
  { character: '&#149;', decimalCode: '&amp;#149;', name: 'Bullet (&amp;bull;)', characterSet: 'ANSI' },
  { character: '&#150;', decimalCode: '&amp;#150;', name: 'En dash (&amp;ndash; or &amp;#8211;)', characterSet: 'ANSI' },
  { character: '&#151;', decimalCode: '&amp;#151;', name: 'Em dash (&amp;mdash; or &amp;#8212;)', characterSet: 'ANSI' },
  { character: '&#163;', decimalCode: '&amp;#163;', name: 'Pound sign (&amp;pound;)', characterSet: 'ANSI' },
  { character: '&#165;', decimalCode: '&amp;#165;', name: 'Yen sign (&amp;yen;)', characterSet: 'ANSI' },
  { character: '&#167;', decimalCode: '&amp;#167;', name: 'Section sign (&amp;sect;)', characterSet: 'ANSI' },
  { character: '&#169;', decimalCode: '&amp;#169;', name: 'Copyright sign (&amp;copy;)', characterSet: 'ANSI' },
  { character: '&#174;', decimalCode: '&amp;#174;', name: 'Registered sign (&amp;reg;)', characterSet: 'ANSI' },
  { character: '&#176;', decimalCode: '&amp;#176;', name: 'Degree sign (&amp;deg;)', characterSet: 'ANSI' },
  { character: '&#177;', decimalCode: '&amp;#177;', name: 'Plus-minus sign (&amp;plusmn;)', characterSet: 'ANSI' },
  { character: '&#182;', decimalCode: '&amp;#182;', name: 'Pilcrow sign (&amp;para;)', characterSet: 'ANSI' },
  { character: '&#188;', decimalCode: '&amp;#188;', name: 'Vulgar fraction one quarter (&amp;frac14;)', characterSet: 'ANSI' },
  { character: '&#189;', decimalCode: '&amp;#189;', name: 'Vulgar fraction one half (&amp;frac12;)', characterSet: 'ANSI' },
  { character: '&#190;', decimalCode: '&amp;#190;', name: 'Vulgar fraction three quarters (&amp;frac34;)', characterSet: 'ANSI' },
  { character: '&#215;', decimalCode: '&amp;#215;', name: 'Multiplication sign (small) (&amp;times;)', characterSet: 'ANSI' },
  { character: '&#8539;', decimalCode: '&amp;#8539;', name: 'Vulgar fraction one eighth', characterSet: 'WGL4' },
  { character: '&#8540;', decimalCode: '&amp;#8540;', name: 'Vulgar fraction three eighths', characterSet: 'WGL4' },
  { character: '&#8541;', decimalCode: '&amp;#8541;', name: 'Vulgar fraction five eighths', characterSet: 'WGL4' },
  { character: '&#8542;', decimalCode: '&amp;#8542;', name: 'Vulgar fraction seven eighths', characterSet: 'WGL4' },
  { character: '&#8592;', decimalCode: '&amp;#8592;', name: 'Leftwards arrow', characterSet: '' },
  { character: '&#8593;', decimalCode: '&amp;#8593;', name: 'Upwards arrow', characterSet: '' },
  { character: '&#8594;', decimalCode: '&amp;#8594;', name: 'Rightwards arrow', characterSet: '' },
  { character: '&#8595;', decimalCode: '&amp;#8595;', name: 'Downwards arrow', characterSet: '' },
  { character: '&#8596;', decimalCode: '&amp;#8596;', name: 'Left right arrow', characterSet: '' },
  { character: '&#8597;', decimalCode: '&amp;#8597;', name: 'Up down arrow', characterSet: 'WGL4' },
  { character: '&#10132;', decimalCode: '&amp;#10132;', name: 'Heavy wide-headed rightwards arrow', characterSet: 'WGL4' },
  { character: '&#9632;', decimalCode: '&amp;#9632;', name: 'Black square', characterSet: 'Wingdings' },
  { character: '&#9633;', decimalCode: '&amp;#9633;', name: 'White square', characterSet: 'Wingdings' },
  { character: '&#9650;', decimalCode: '&amp;#9650;', name: 'Black up-pointing triangle', characterSet: 'WGL4' },
  { character: '&#9658;', decimalCode: '&amp;#9658;', name: 'Black right-pointing pointer', characterSet: 'WGL4' },
  { character: '&#9660;', decimalCode: '&amp;#9660;', name: 'Black down-pointing triangle', characterSet: 'WGL4' },
  { character: '&#9668;', decimalCode: '&amp;#9668;', name: 'Black left-pointing pointer', characterSet: 'WGL4' },
  { character: '&#9679;', decimalCode: '&amp;#9679;', name: 'Black circle', characterSet: 'Wingdings' },
  { character: '&#9687;', decimalCode: '&amp;#9687;', name: 'Right half moon bullet', characterSet: '' },
  { character: '&#9686;', decimalCode: '&amp;#9686;', name: 'Left half moon bullet', characterSet: '' },
  { character: '&#9744;', decimalCode: '&amp;#9744;', name: 'Ballot Box', characterSet: '' },
  { character: '&#9745;', decimalCode: '&amp;#9745;', name: 'Ballot box with check', characterSet: 'Wingdings' },
  { character: '&#9746;', decimalCode: '&amp;#9746;', name: 'Ballot box with x', characterSet: 'Wingdings' },
  { character: '&#10003;', decimalCode: '&amp;#10003;', name: 'Check mark', characterSet: 'Wingdings' },
  { character: '&#10005;', decimalCode: '&amp;#10005;', name: 'Multiplication x', characterSet: 'Wingdings' },
  { character: '&#10146;', decimalCode: '&amp;#10146;', name: 'Three-d top-lighted rightwards arrowhead', characterSet: 'Wingdings' },
  { character: '&#96;', decimalCode: '&amp;#96;', name: 'Grave accent', characterSet: 'WGL4' },
  { character: '&#129;', decimalCode: '&amp;#129;', name: '(Not used)', characterSet: 'ANSI' },
  { character: '&#130;', decimalCode: '&amp;#130;', name: 'Single low-9 quotation mark (&amp;sbquo;)', characterSet: 'ANSI' },
  { character: '&#131;', decimalCode: '&amp;#131;', name: 'Latin small letter f with hook (&amp;fnof;)', characterSet: 'ANSI' },
  { character: '&#132;', decimalCode: '&amp;#132;', name: 'Double low-9 quotation mark (&amp;bdquo;)', characterSet: 'ANSI' },
  { character: '&#133;', decimalCode: '&amp;#133;', name: 'Horizontal ellipsis (&amp;hellip;)', characterSet: 'ANSI' },
  { character: '&#136;', decimalCode: '&amp;#136;', name: 'Modifier letter circumflex accent (&amp;circ;)', characterSet: 'ANSI' },
  { character: '&#137;', decimalCode: '&amp;#137;', name: 'Per mille sign (&amp;permil;)', characterSet: 'ANSI' },
  { character: '&#138;', decimalCode: '&amp;#138;', name: 'Latin capital letter s with caron (&amp;scaron;)', characterSet: 'ANSI' },
  { character: '&#139;', decimalCode: '&amp;#139;', name: 'Single left-pointing angle quotation mark (&amp;lsaquo;)', characterSet: 'ANSI' },
  { character: '&#140;', decimalCode: '&amp;#140;', name: 'Latin capital ligature oe (&amp;oelig;)', characterSet: 'ANSI' },
  { character: '&#141;', decimalCode: '&amp;#141;', name: '(Not used)', characterSet: 'ANSI' },
  { character: '&#142;', decimalCode: '&amp;#142;', name: 'Latin capital letter z with caron', characterSet: 'ANSI' },
  { character: '&#143;', decimalCode: '&amp;#143;', name: '(Not used)', characterSet: 'ANSI' },
  { character: '&#144;', decimalCode: '&amp;#144;', name: '(Not used)', characterSet: 'ANSI' },
  { character: '&#145;', decimalCode: '&amp;#145;', name: 'Left single quotation mark (&amp;lsquo; or &amp;#8216;)', characterSet: 'ANSI' },
  { character: '&#146;', decimalCode: '&amp;#146;', name: 'Right single quotation mark (&amp;rsquo; or &amp;#8217;)', characterSet: 'ANSI' },
  { character: '&#147;', decimalCode: '&amp;#147;', name: 'Left double quotation mark (&amp;ldquo; or &amp;#8220;)', characterSet: 'ANSI' },
  { character: '&#148;', decimalCode: '&amp;#148;', name: 'Right double quotation mark (&amp;rdquo; or &amp;#8221;)', characterSet: 'ANSI' },
  { character: '&#152;', decimalCode: '&amp;#152;', name: 'Small tilde (&amp;tilde; or &amp;#732;)', characterSet: 'ANSI' },
  { character: '&#153;', decimalCode: '&amp;#153;', name: 'Trade mark sign (&amp;trade;)', characterSet: 'ANSI' },
  { character: '&#154;', decimalCode: '&amp;#154;', name: 'Latin small letter s with caron (&amp;scaron;)', characterSet: 'ANSI' },
  { character: '&#155;', decimalCode: '&amp;#155;', name: 'Single right-pointing angle quotation mark (&amp;rsaquo;)', characterSet: 'ANSI' },
  { character: '&#156;', decimalCode: '&amp;#156;', name: 'Latin small ligature oe (&amp;oelig;)', characterSet: 'ANSI' },
  { character: '&#157;', decimalCode: '&amp;#157;', name: '(Not used)', characterSet: 'ANSI' },
  { character: '&#158;', decimalCode: '&amp;#158;', name: 'Latin small letter z with caron', characterSet: 'ANSI' },
  { character: '&#159;', decimalCode: '&amp;#159;', name: 'Latin capital letter y with diaeresis (&amp;yuml;)', characterSet: 'ANSI' },
  { character: '&#160;', decimalCode: '&amp;#160;', name: 'No-break space (&amp;nbsp;)', characterSet: 'ANSI' },
  { character: '&#161;', decimalCode: '&amp;#161;', name: 'Inverted exclamation mark (&amp;iexcl;)', characterSet: 'ANSI' },
  { character: '&#162;', decimalCode: '&amp;#162;', name: 'Cent sign (&amp;cent;)', characterSet: 'ANSI' },
  { character: '&#164;', decimalCode: '&amp;#164;', name: 'Currency sign (&amp;curren;)', characterSet: 'ANSI' },
  { character: '&#166;', decimalCode: '&amp;#166;', name: 'Broken bar (&amp;brvbar;)', characterSet: 'ANSI' },
  { character: '&#168;', decimalCode: '&amp;#168;', name: 'Diaeresis (&amp;uml;)', characterSet: 'ANSI' },
  { character: '&#170;', decimalCode: '&amp;#170;', name: 'Feminine ordinal indicator (&amp;ordf;)', characterSet: 'ANSI' },
  { character: '&#171;', decimalCode: '&amp;#171;', name: 'Left-pointing double angle quotation mark (&amp;laquo;)', characterSet: 'ANSI' },
  { character: '&#172;', decimalCode: '&amp;#172;', name: 'Not sign (&amp;not;)', characterSet: 'ANSI' },
  { character: '&#173;', decimalCode: '&amp;#173;', name: 'Soft hyphen (&amp;shy;)', characterSet: 'ANSI' },
  { character: '&#175;', decimalCode: '&amp;#175;', name: 'Macron (&amp;macr;)', characterSet: 'ANSI' },
  { character: '&#178;', decimalCode: '&amp;#178;', name: 'Superscript two (&amp;sup2;)', characterSet: 'ANSI' },
  { character: '&#179;', decimalCode: '&amp;#179;', name: 'Superscript three (&amp;sup3;)', characterSet: 'ANSI' },
  { character: '&#180;', decimalCode: '&amp;#180;', name: 'Acute accent (&amp;acute;)', characterSet: 'ANSI' },
  { character: '&#181;', decimalCode: '&amp;#181;', name: 'Micro sign (&amp;micro;)', characterSet: 'ANSI' },
  { character: '&#183;', decimalCode: '&amp;#183;', name: 'Middle dot (&amp;middot;)', characterSet: 'ANSI' },
  { character: '&#184;', decimalCode: '&amp;#184;', name: 'Cedilla (&amp;cedil;)', characterSet: 'ANSI' },
  { character: '&#185;', decimalCode: '&amp;#185;', name: 'Superscript one (&amp;sup1;)', characterSet: 'ANSI' },
  { character: '&#186;', decimalCode: '&amp;#186;', name: 'Masculine ordinal indicator (&amp;ordm;)', characterSet: 'ANSI' },
  { character: '&#187;', decimalCode: '&amp;#187;', name: 'Right-pointing double angle quotation mark (&amp;raquo;)', characterSet: 'ANSI' },
  { character: '&#191;', decimalCode: '&amp;#191;', name: 'Inverted question mark (&amp;iquest;)', characterSet: 'ANSI' },
  { character: '&#192;', decimalCode: '&amp;#192;', name: 'Latin capital letter a with grave (&amp;agrave;)', characterSet: 'ANSI' },
  { character: '&#193;', decimalCode: '&amp;#193;', name: 'Latin capital letter a with acute (&amp;aacute;)', characterSet: 'ANSI' },
  { character: '&#194;', decimalCode: '&amp;#194;', name: 'Latin capital letter a with circumflex (&amp;acirc;)', characterSet: 'ANSI' },
  { character: '&#195;', decimalCode: '&amp;#195;', name: 'Latin capital letter a with tilde (&amp;atilde;)', characterSet: 'ANSI' },
  { character: '&#196;', decimalCode: '&amp;#196;', name: 'Latin capital letter a with diaeresis (&amp;auml;)', characterSet: 'ANSI' },
  { character: '&#197;', decimalCode: '&amp;#197;', name: 'Latin capital letter a with ring above (&amp;aring;)', characterSet: 'ANSI' },
  { character: '&#198;', decimalCode: '&amp;#198;', name: 'Latin capital letter ae (&amp;aelig;)', characterSet: 'ANSI' },
  { character: '&#199;', decimalCode: '&amp;#199;', name: 'Latin capital letter c with cedilla (&amp;ccedil;)', characterSet: 'ANSI' },
  { character: '&#200;', decimalCode: '&amp;#200;', name: 'Latin capital letter e with grave (&amp;egrave;)', characterSet: 'ANSI' },
  { character: '&#201;', decimalCode: '&amp;#201;', name: 'Latin capital letter e with acute (&amp;eacute;)', characterSet: 'ANSI' },
  { character: '&#202;', decimalCode: '&amp;#202;', name: 'Latin capital letter e with circumflex (&amp;ecirc;)', characterSet: 'ANSI' },
  { character: '&#203;', decimalCode: '&amp;#203;', name: 'Latin capital letter e with diaeresis (&amp;euml;)', characterSet: 'ANSI' },
  { character: '&#204;', decimalCode: '&amp;#204;', name: 'Latin capital letter i with grave (&amp;igrave;)', characterSet: 'ANSI' },
  { character: '&#205;', decimalCode: '&amp;#205;', name: 'Latin capital letter i with acute (&amp;iacute;)', characterSet: 'ANSI' },
  { character: '&#206;', decimalCode: '&amp;#206;', name: 'Latin capital letter i with circumflex (&amp;icirc;)', characterSet: 'ANSI' },
  { character: '&#207;', decimalCode: '&amp;#207;', name: 'Latin capital letter i with diaeresis (&amp;iuml;)', characterSet: 'ANSI' },
  { character: '&#208;', decimalCode: '&amp;#208;', name: 'Latin capital letter eth (&amp;eth;)', characterSet: 'ANSI' },
  { character: '&#209;', decimalCode: '&amp;#209;', name: 'Latin capital letter n with tilde (&amp;ntilde;)', characterSet: 'ANSI' },
  { character: '&#210;', decimalCode: '&amp;#210;', name: 'Latin capital letter o with grave (&amp;ograve;)', characterSet: 'ANSI' },
  { character: '&#211;', decimalCode: '&amp;#211;', name: 'Latin capital letter o with acute (&amp;oacute;)', characterSet: 'ANSI' },
  { character: '&#212;', decimalCode: '&amp;#212;', name: 'Latin capital letter o with circumflex (&amp;ocirc;)', characterSet: 'ANSI' },
  { character: '&#213;', decimalCode: '&amp;#213;', name: 'Latin capital letter o with tilde (&amp;otilde;)', characterSet: 'ANSI' },
  { character: '&#214;', decimalCode: '&amp;#214;', name: 'Latin capital letter o with diaeresis (&amp;ouml;)', characterSet: 'ANSI' },
  { character: '&#216;', decimalCode: '&amp;#216;', name: 'Latin capital letter o with stroke (&amp;oslash;)', characterSet: 'ANSI' },
  { character: '&#217;', decimalCode: '&amp;#217;', name: 'Latin capital letter u with grave (&amp;ugrave;)', characterSet: 'ANSI' },
  { character: '&#218;', decimalCode: '&amp;#218;', name: 'Latin capital letter u with acute (&amp;uacute;)', characterSet: 'ANSI' },
  { character: '&#219;', decimalCode: '&amp;#219;', name: 'Latin capital letter u with circumflex (&amp;ucirc;)', characterSet: 'ANSI' },
  { character: '&#220;', decimalCode: '&amp;#220;', name: 'Latin capital letter u with diaeresis (&amp;uuml;)', characterSet: 'ANSI' },
  { character: '&#221;', decimalCode: '&amp;#221;', name: 'Latin capital letter y with acute (&amp;yacute;)', characterSet: 'ANSI' },
  { character: '&#222;', decimalCode: '&amp;#222;', name: 'Latin capital letter thorn (&amp;thorn;)', characterSet: 'ANSI' },
  { character: '&#223;', decimalCode: '&amp;#223;', name: 'Latin small letter sharp s (&amp;szlig;)', characterSet: 'ANSI' },
  { character: '&#224;', decimalCode: '&amp;#224;', name: 'Latin small letter a with grave (&amp;agrave;)', characterSet: 'ANSI' },
  { character: '&#225;', decimalCode: '&amp;#225;', name: 'Latin small letter a with acute (&amp;aacute;)', characterSet: 'ANSI' },
  { character: '&#226;', decimalCode: '&amp;#226;', name: 'Latin small letter a with circumflex (&amp;acirc;)', characterSet: 'ANSI' },
  { character: '&#227;', decimalCode: '&amp;#227;', name: 'Latin small letter a with tilde (&amp;atilde;)', characterSet: 'ANSI' },
  { character: '&#228;', decimalCode: '&amp;#228;', name: 'Latin small letter a with diaeresis (&amp;auml;)', characterSet: 'ANSI' },
  { character: '&#229;', decimalCode: '&amp;#229;', name: 'Latin small letter a with ring above (&amp;aring;)', characterSet: 'ANSI' },
  { character: '&#230;', decimalCode: '&amp;#230;', name: 'Latin small letter ae (&amp;aelig;)', characterSet: 'ANSI' },
  { character: '&#231;', decimalCode: '&amp;#231;', name: 'Latin small letter c with cedilla (&amp;ccedil;)', characterSet: 'ANSI' },
  { character: '&#232;', decimalCode: '&amp;#232;', name: 'Latin small letter e with grave (&amp;egrave;)', characterSet: 'ANSI' },
  { character: '&#233;', decimalCode: '&amp;#233;', name: 'Latin small letter e with acute (&amp;eacute;)', characterSet: 'ANSI' },
  { character: '&#234;', decimalCode: '&amp;#234;', name: 'Latin small letter e with circumflex (&amp;ecirc;)', characterSet: 'ANSI' },
  { character: '&#235;', decimalCode: '&amp;#235;', name: 'Latin small letter e with diaeresis (&amp;euml;)', characterSet: 'ANSI' },
  { character: '&#236;', decimalCode: '&amp;#236;', name: 'Latin small letter i with grave (&amp;igrave;)', characterSet: 'ANSI' },
  { character: '&#237;', decimalCode: '&amp;#237;', name: 'Latin small letter i with acute (&amp;iacute;)', characterSet: 'ANSI' },
  { character: '&#238;', decimalCode: '&amp;#238;', name: 'Latin small letter i with circumflex (&amp;icirc;)', characterSet: 'ANSI' },
  { character: '&#239;', decimalCode: '&amp;#239;', name: 'Latin small letter i with diaeresis (&amp;iuml;)', characterSet: 'ANSI' },
  { character: '&#240;', decimalCode: '&amp;#240;', name: 'Latin small letter eth (&amp;eth;)', characterSet: 'ANSI' },
  { character: '&#241;', decimalCode: '&amp;#241;', name: 'Latin small letter n with tilde (&amp;ntilde;)', characterSet: 'ANSI' },
  { character: '&#242;', decimalCode: '&amp;#242;', name: 'Latin small letter o with grave (&amp;ograve;)', characterSet: 'ANSI' },
  { character: '&#243;', decimalCode: '&amp;#243;', name: 'Latin small letter o with acute (&amp;oacute;)', characterSet: 'ANSI' },
  { character: '&#244;', decimalCode: '&amp;#244;', name: 'Latin small letter o with circumflex (&amp;ocirc;)', characterSet: 'ANSI' },
  { character: '&#245;', decimalCode: '&amp;#245;', name: 'Latin small letter o with tilde (&amp;otilde;)', characterSet: 'ANSI' },
  { character: '&#246;', decimalCode: '&amp;#246;', name: 'Latin small letter o with diaeresis (&amp;ouml;)', characterSet: 'ANSI' },
  { character: '&#247;', decimalCode: '&amp;#247;', name: 'Division sign (&amp;divide;)', characterSet: 'ANSI' },
  { character: '&#248;', decimalCode: '&amp;#248;', name: 'Latin small letter o with stroke (&amp;oslash;)', characterSet: 'ANSI' },
  { character: '&#249;', decimalCode: '&amp;#249;', name: 'Latin small letter u with grave (&amp;ugrave;)', characterSet: 'ANSI' },
  { character: '&#250;', decimalCode: '&amp;#250;', name: 'Latin small letter u with acute (&amp;uacute;)', characterSet: 'ANSI' },
  { character: '&#251;', decimalCode: '&amp;#251;', name: 'Latin small letter with circumflex (&amp;ucirc;)', characterSet: 'ANSI' },
  { character: '&#252;', decimalCode: '&amp;#252;', name: 'Latin small letter u with diaeresis (&amp;uuml;)', characterSet: 'ANSI' },
  { character: '&#253;', decimalCode: '&amp;#253;', name: 'Latin small letter y with acute (&amp;yacute;)', characterSet: 'ANSI' },
  { character: '&#254;', decimalCode: '&amp;#254;', name: 'Latin small letter thorn (&amp;thorn;)', characterSet: 'ANSI' },
  { character: '&#255;', decimalCode: '&amp;#255;', name: 'Latin small letter y with diaeresis (&amp;yuml;)', characterSet: 'ANSI' },
  { character: '&#256;', decimalCode: '&amp;#256;', name: 'Latin capital letter a with macron', characterSet: 'WGL4' },
  { character: '&#257;', decimalCode: '&amp;#257;', name: 'Latin small letter a with macron', characterSet: 'WGL4' },
  { character: '&#258;', decimalCode: '&amp;#258;', name: 'Latin capital letter a with breve', characterSet: 'WGL4' },
  { character: '&#259;', decimalCode: '&amp;#259;', name: 'Latin small letter a with breve', characterSet: 'WGL4' },
  { character: '&#260;', decimalCode: '&amp;#260;', name: 'Latin capital letter a with ogonek', characterSet: 'WGL4' },
  { character: '&#261;', decimalCode: '&amp;#261;', name: 'Latin small letter a with ogonek', characterSet: 'WGL4' },
  { character: '&#262;', decimalCode: '&amp;#262;', name: 'Latin capital letter c with acute', characterSet: 'WGL4' },
  { character: '&#263;', decimalCode: '&amp;#263;', name: 'Latin small letter c with acute', characterSet: 'WGL4' },
  { character: '&#264;', decimalCode: '&amp;#264;', name: 'Latin capital letter c with circumflex', characterSet: 'WGL4' },
  { character: '&#265;', decimalCode: '&amp;#265;', name: 'Latin small letter c with circumflex', characterSet: 'WGL4' },
  { character: '&#266;', decimalCode: '&amp;#266;', name: 'Latin capital letter c with dot above', characterSet: 'WGL4' },
  { character: '&#267;', decimalCode: '&amp;#267;', name: 'Latin small letter c with dot above', characterSet: 'WGL4' },
  { character: '&#268;', decimalCode: '&amp;#268;', name: 'Latin capital letter c with caron', characterSet: 'WGL4' },
  { character: '&#269;', decimalCode: '&amp;#269;', name: 'Latin small letter c with caron', characterSet: 'WGL4' },
  { character: '&#270;', decimalCode: '&amp;#270;', name: 'Latin capital letter d with caron', characterSet: 'WGL4' },
  { character: '&#271;', decimalCode: '&amp;#271;', name: 'Latin small letter d with caron', characterSet: 'WGL4' },
  { character: '&#272;', decimalCode: '&amp;#272;', name: 'Latin capital letter d with stroke', characterSet: 'WGL4' },
  { character: '&#273;', decimalCode: '&amp;#273;', name: 'Latin small letter d with stroke', characterSet: 'WGL4' },
  { character: '&#274;', decimalCode: '&amp;#274;', name: 'Latin capital letter e with macron', characterSet: 'WGL4' },
  { character: '&#275;', decimalCode: '&amp;#275;', name: 'Latin small letter e with macron', characterSet: 'WGL4' },
  { character: '&#276;', decimalCode: '&amp;#276;', name: 'Latin capital letter e with breve', characterSet: 'WGL4' },
  { character: '&#277;', decimalCode: '&amp;#277;', name: 'Latin small letter e with breve', characterSet: 'WGL4' },
  { character: '&#278;', decimalCode: '&amp;#278;', name: 'Latin capital letter e with dot above', characterSet: 'WGL4' },
  { character: '&#279;', decimalCode: '&amp;#279;', name: 'Latin small letter e with dot above', characterSet: 'WGL4' },
  { character: '&#280;', decimalCode: '&amp;#280;', name: 'Latin capital letter e with ogenek', characterSet: 'WGL4' },
  { character: '&#281;', decimalCode: '&amp;#281;', name: 'Latin small letter e with ogenek', characterSet: 'WGL4' },
  { character: '&#282;', decimalCode: '&amp;#282;', name: 'Latin capital letter e with caron', characterSet: 'WGL4' },
  { character: '&#283;', decimalCode: '&amp;#283;', name: 'Latin small letter e with caron', characterSet: 'WGL4' },
  { character: '&#284;', decimalCode: '&amp;#284;', name: 'Latin capital letter g with circumflex', characterSet: 'WGL4' },
  { character: '&#285;', decimalCode: '&amp;#285;', name: 'Latin small letter g with circumflex', characterSet: 'WGL4' },
  { character: '&#286;', decimalCode: '&amp;#286;', name: 'Latin capital letter g with breve', characterSet: 'WGL4' },
  { character: '&#287;', decimalCode: '&amp;#287;', name: 'Latin small letter g with breve', characterSet: 'WGL4' },
  { character: '&#288;', decimalCode: '&amp;#288;', name: 'Latin capital letter g with dot above', characterSet: 'WGL4' },
  { character: '&#289;', decimalCode: '&amp;#289;', name: 'Latin small letter g with dot above', characterSet: 'WGL4' },
  { character: '&#290;', decimalCode: '&amp;#290;', name: 'Latin capital letter g with cedilla', characterSet: 'WGL4' },
  { character: '&#291;', decimalCode: '&amp;#291;', name: 'Latin small letter g with cedilla', characterSet: 'WGL4' },
  { character: '&#292;', decimalCode: '&amp;#292;', name: 'Latin capital letter h with circumflex', characterSet: 'WGL4' },
  { character: '&#293;', decimalCode: '&amp;#293;', name: 'Latin small letter h with circumflex', characterSet: 'WGL4' },
  { character: '&#294;', decimalCode: '&amp;#294;', name: 'Latin capital letter h with stroke', characterSet: 'WGL4' },
  { character: '&#295;', decimalCode: '&amp;#295;', name: 'Latin small letter h with stroke', characterSet: 'WGL4' },
  { character: '&#296;', decimalCode: '&amp;#296;', name: 'Latin capital letter i with tilde', characterSet: 'WGL4' },
  { character: '&#297;', decimalCode: '&amp;#297;', name: 'Latin small letter i with tilde', characterSet: 'WGL4' },
  { character: '&#298;', decimalCode: '&amp;#298;', name: 'Latin capital letter i with macron', characterSet: 'WGL4' },
  { character: '&#299;', decimalCode: '&amp;#299;', name: 'Latin small letter i with macron', characterSet: 'WGL4' },
  { character: '&#300;', decimalCode: '&amp;#300;', name: 'Latin capital letter i with breve', characterSet: 'WGL4' },
  { character: '&#301;', decimalCode: '&amp;#301;', name: 'Latin small letter i with breve', characterSet: 'WGL4' },
  { character: '&#303;', decimalCode: '&amp;#303;', name: 'Latin small letter i with ogonek', characterSet: 'WGL4' },
  { character: '&#304;', decimalCode: '&amp;#304;', name: 'Latin capital letter i with dot above', characterSet: 'WGL4' },
  { character: '&#305;', decimalCode: '&amp;#305;', name: 'Latin small letter dotless i', characterSet: 'WGL4' },
  { character: '&#306;', decimalCode: '&amp;#306;', name: 'Latin capital ligature ij', characterSet: 'WGL4' },
  { character: '&#307;', decimalCode: '&amp;#307;', name: 'Latin small ligature ij', characterSet: 'WGL4' },
  { character: '&#308;', decimalCode: '&amp;#308;', name: 'Latin capital letter j with circumflex', characterSet: 'WGL4' },
  { character: '&#309;', decimalCode: '&amp;#309;', name: 'Latin small letter j with circumflex', characterSet: 'WGL4' },
  { character: '&#310;', decimalCode: '&amp;#310;', name: 'Latin capital letter k with cedilla', characterSet: 'WGL4' },
  { character: '&#311;', decimalCode: '&amp;#311;', name: 'Latin small letter k with cedilla', characterSet: 'WGL4' },
  { character: '&#312;', decimalCode: '&amp;#312;', name: 'Latin small letter kra', characterSet: 'WGL4' },
  { character: '&#313;', decimalCode: '&amp;#313;', name: 'Latin capital letter l with acute', characterSet: 'WGL4' },
  { character: '&#314;', decimalCode: '&amp;#314;', name: 'Latin small letter l with acute', characterSet: 'WGL4' },
  { character: '&#315;', decimalCode: '&amp;#315;', name: 'Latin capital letter l with cedilla', characterSet: 'WGL4' },
  { character: '&#316;', decimalCode: '&amp;#316;', name: 'Latin small letter l with cedilla', characterSet: 'WGL4' },
  { character: '&#317;', decimalCode: '&amp;#317;', name: 'Latin capital letter l with caron', characterSet: 'WGL4' },
  { character: '&#318;', decimalCode: '&amp;#318;', name: 'Latin small letter l with caron', characterSet: 'WGL4' },
  { character: '&#319;', decimalCode: '&amp;#319;', name: 'Latin capital letter l with middle dot', characterSet: 'WGL4' },
  { character: '&#320;', decimalCode: '&amp;#320;', name: 'Latin small letter l with middle dot', characterSet: 'WGL4' },
  { character: '&#321;', decimalCode: '&amp;#321;', name: 'Latin capital letter l with stroke', characterSet: 'WGL4' },
  { character: '&#322;', decimalCode: '&amp;#322;', name: 'Latin small letter l with stroke', characterSet: 'WGL4' },
  { character: '&#323;', decimalCode: '&amp;#323;', name: 'Latin capital letter n with acute', characterSet: 'WGL4' },
  { character: '&#324;', decimalCode: '&amp;#324;', name: 'Latin small letter n with acute', characterSet: 'WGL4' },
  { character: '&#325;', decimalCode: '&amp;#325;', name: 'Latin capital letter n with cedilla', characterSet: 'WGL4' },
  { character: '&#326;', decimalCode: '&amp;#326;', name: 'Latin small letter n with cedilla', characterSet: 'WGL4' },
  { character: '&#327;', decimalCode: '&amp;#327;', name: 'Latin capital letter n with caron', characterSet: 'WGL4' },
  { character: '&#328;', decimalCode: '&amp;#328;', name: 'Latin small letter n with caron', characterSet: 'WGL4' },
  { character: '&#329;', decimalCode: '&amp;#329;', name: 'Latin small letter n preceded by apostrophe', characterSet: 'WGL4' },
  { character: '&#330;', decimalCode: '&amp;#330;', name: 'Latin capital letter eng', characterSet: 'WGL4' },
  { character: '&#331;', decimalCode: '&amp;#331;', name: 'Latin small letter eng', characterSet: 'WGL4' },
  { character: '&#332;', decimalCode: '&amp;#332;', name: 'Latin capital letter o with macron', characterSet: 'WGL4' },
  { character: '&#333;', decimalCode: '&amp;#333;', name: 'Latin small letter o with macron', characterSet: 'WGL4' },
  { character: '&#334;', decimalCode: '&amp;#334;', name: 'Latin capital letter o with breve', characterSet: 'WGL4' },
  { character: '&#335;', decimalCode: '&amp;#335;', name: 'Latin small letter o with breve', characterSet: 'WGL4' },
  { character: '&#336;', decimalCode: '&amp;#336;', name: 'Latin capital letter o with double acute', characterSet: 'WGL4' },
  { character: '&#337;', decimalCode: '&amp;#337;', name: 'Latin small letter o with double acute', characterSet: 'WGL4' },
  { character: '&#338;', decimalCode: '&amp;#338;', name: 'Latin capital ligature oe', characterSet: 'WGL4' },
  { character: '&#339;', decimalCode: '&amp;#339;', name: 'Latin small ligature oe', characterSet: 'WGL4' },
  { character: '&#340;', decimalCode: '&amp;#340;', name: 'Latin capital letter r with acute', characterSet: 'WGL4' },
  { character: '&#341;', decimalCode: '&amp;#341;', name: 'Latin small letter r with acute', characterSet: 'WGL4' },
  { character: '&#342;', decimalCode: '&amp;#342;', name: 'Latin capital letter r with cedilla', characterSet: 'WGL4' },
  { character: '&#343;', decimalCode: '&amp;#343;', name: 'Latin small letter r with cedilla', characterSet: 'WGL4' },
  { character: '&#344;', decimalCode: '&amp;#344;', name: 'Latin capital letter r with caron', characterSet: 'WGL4' },
  { character: '&#345;', decimalCode: '&amp;#345;', name: 'Latin small letter r with caron', characterSet: 'WGL4' },
  { character: '&#346;', decimalCode: '&amp;#346;', name: 'Latin capital letter s with acute', characterSet: 'WGL4' },
  { character: '&#347;', decimalCode: '&amp;#347;', name: 'Latin small letter s with acute', characterSet: 'WGL4' },
  { character: '&#348;', decimalCode: '&amp;#348;', name: 'Latin capital letter s with circumflex', characterSet: 'WGL4' },
  { character: '&#349;', decimalCode: '&amp;#349;', name: 'Latin small letter s with circumflex', characterSet: 'WGL4' },
  { character: '&#350;', decimalCode: '&amp;#350;', name: 'Latin capital letter s with cedilla', characterSet: 'WGL4' },
  { character: '&#351;', decimalCode: '&amp;#351;', name: 'Latin small letter s with cedilla', characterSet: 'WGL4' },
  { character: '&#352;', decimalCode: '&amp;#352;', name: 'Latin capital letter s with caron ', characterSet: 'Differences' },
  { character: '&#353;', decimalCode: '&amp;#353;', name: 'Latin small letter s with caron', characterSet: 'Differences' },
  { character: '&#354;', decimalCode: '&amp;#354;', name: 'Latin capital letter t with cedilla', characterSet: 'WGL4' },
  { character: '&#355;', decimalCode: '&amp;#355;', name: 'Latin small letter t with cedilla', characterSet: 'WGL4' },
  { character: '&#356;', decimalCode: '&amp;#356;', name: 'Latin capital letter t with caron', characterSet: 'WGL4' },
  { character: '&#357;', decimalCode: '&amp;#357;', name: 'Latin small letter t with caron', characterSet: 'WGL4' },
  { character: '&#358;', decimalCode: '&amp;#358;', name: 'Latin capital letter t with stroke', characterSet: 'WGL4' },
  { character: '&#359;', decimalCode: '&amp;#359;', name: 'Latin small letter t with stroke', characterSet: 'WGL4' },
  { character: '&#360;', decimalCode: '&amp;#360;', name: 'Latin capital letter u with tilde', characterSet: 'WGL4' },
  { character: '&#361;', decimalCode: '&amp;#361;', name: 'Latin small letter u with tilde', characterSet: 'WGL4' },
  { character: '&#362;', decimalCode: '&amp;#362;', name: 'Latin capital letter u with macron', characterSet: 'WGL4' },
  { character: '&#363;', decimalCode: '&amp;#363;', name: 'Latin small letter u with macron', characterSet: 'WGL4' },
  { character: '&#364;', decimalCode: '&amp;#364;', name: 'Latin capital letter u with breve', characterSet: 'WGL4' },
  { character: '&#365;', decimalCode: '&amp;#365;', name: 'Latin small letter u with breve', characterSet: 'WGL4' },
  { character: '&#366;', decimalCode: '&amp;#366;', name: 'Latin capital letter u with ring above', characterSet: 'WGL4' },
  { character: '&#367;', decimalCode: '&amp;#367;', name: 'Latin small letter u with ring above', characterSet: 'WGL4' },
  { character: '&#368;', decimalCode: '&amp;#368;', name: 'Latin capital letter u with double acute', characterSet: 'WGL4' },
  { character: '&#369;', decimalCode: '&amp;#369;', name: 'Latin small letter u with double acute', characterSet: 'WGL4' },
  { character: '&#370;', decimalCode: '&amp;#370;', name: 'Latin capital letter u with ogonek', characterSet: 'WGL4' },
  { character: '&#371;', decimalCode: '&amp;#371;', name: 'Latin small letter u with ogonek', characterSet: 'WGL4' },
  { character: '&#372;', decimalCode: '&amp;#372;', name: 'Latin capital letter w with circumflex', characterSet: 'WGL4' },
  { character: '&#373;', decimalCode: '&amp;#373;', name: 'Latin small letter w with circumflex', characterSet: 'WGL4' },
  { character: '&#374;', decimalCode: '&amp;#374;', name: 'Latin capital letter y with circumflex', characterSet: 'WGL4' },
  { character: '&#375;', decimalCode: '&amp;#375;', name: 'Latin small letter y with circumflex', characterSet: 'WGL4' },
  { character: '&#376;', decimalCode: '&amp;#376;', name: 'Latin capital letter y with diaeresis', characterSet: 'WGL4' },
  { character: '&#377;', decimalCode: '&amp;#377;', name: 'Latin capital letter z with acute', characterSet: 'WGL4' },
  { character: '&#378;', decimalCode: '&amp;#378;', name: 'Latin small letter z with acute', characterSet: 'WGL4' },
  { character: '&#379;', decimalCode: '&amp;#379;', name: 'Latin capital letter z with dot above', characterSet: 'WGL4' },
  { character: '&#380;', decimalCode: '&amp;#380;', name: 'Latin small letter z with dot above', characterSet: 'WGL4' },
  { character: '&#381;', decimalCode: '&amp;#381;', name: 'Latin capital letter z with caron', characterSet: 'Differences' },
  { character: '&#382;', decimalCode: '&amp;#382;', name: 'Latin small letter z with caron', characterSet: 'Differences' },
  { character: '&#383;', decimalCode: '&amp;#383;', name: 'Latin small letter long s', characterSet: 'WGL4' },
  { character: '&#402;', decimalCode: '&amp;#402;', name: 'Latin small letter f with hook', characterSet: '' },
  { character: '&#506;', decimalCode: '&amp;#506;', name: 'Latin capital letter a with ring above and acute', characterSet: 'WGL4' },
  { character: '&#507;', decimalCode: '&amp;#507;', name: 'Latin small letter a with ring above and acute', characterSet: 'WGL4' },
  { character: '&#508;', decimalCode: '&amp;#508;', name: 'Latin capital letter ae with acute', characterSet: 'WGL4' },
  { character: '&#509;', decimalCode: '&amp;#509;', name: 'Latin small letter ae with acute', characterSet: 'WGL4' },
  { character: '&#510;', decimalCode: '&amp;#510;', name: 'Latin capital letter o with stroke and acute', characterSet: 'WGL4' },
  { character: '&#511;', decimalCode: '&amp;#511;', name: 'Latin small letter o with stroke and acute', characterSet: 'WGL4' },
  { character: '&#710;', decimalCode: '&amp;#710;', name: 'Modifier letter circumflex accent', characterSet: 'WGL4' },
  { character: '&#711;', decimalCode: '&amp;#711;', name: 'Caron', characterSet: 'WGL4' },
  { character: '&#713;', decimalCode: '&amp;#713;', name: 'Modifier letter macron', characterSet: 'WGL4' },
  { character: '&#728;', decimalCode: '&amp;#728;', name: 'Breve', characterSet: 'WGL4' },
  { character: '&#729;', decimalCode: '&amp;#729;', name: 'Dot above', characterSet: 'WGL4' },
  { character: '&#730;', decimalCode: '&amp;#730;', name: 'Ring above', characterSet: 'WGL4' },
  { character: '&#731;', decimalCode: '&amp;#731;', name: 'Ogonek', characterSet: 'WGL4' },
  { character: '&#733;', decimalCode: '&amp;#733;', name: 'Double acute accent', characterSet: 'WGL4' },
  { character: '&#900;', decimalCode: '&amp;#900;', name: 'Greek tonos', characterSet: 'WGL4' },
  { character: '&#901;', decimalCode: '&amp;#901;', name: 'Greek dialytika tonos', characterSet: 'WGL4' },
  { character: '&#902;', decimalCode: '&amp;#902;', name: 'Greek capital letter alpha with tonos', characterSet: 'WGL4' },
  { character: '&#903;', decimalCode: '&amp;#903;', name: 'Greek ano teleia', characterSet: 'WGL4' },
  { character: '&#904;', decimalCode: '&amp;#904;', name: 'Greek capital letter epsilon with tonos', characterSet: 'WGL4' },
  { character: '&#905;', decimalCode: '&amp;#905;', name: 'Greek capital letter eta with tonos', characterSet: 'WGL4' },
  { character: '&#906;', decimalCode: '&amp;#906;', name: 'Greek capital letter iota with tonos', characterSet: 'WGL4' },
  { character: '&#908;', decimalCode: '&amp;#908;', name: 'Greek capital letter omicron with tonos', characterSet: 'WGL4' },
  { character: '&#910;', decimalCode: '&amp;#910;', name: 'Greek capital letter upsilon with tonos', characterSet: 'WGL4' },
  { character: '&#911;', decimalCode: '&amp;#911;', name: 'Greek capital letter omega with tonos', characterSet: 'WGL4' },
  { character: '&#912;', decimalCode: '&amp;#912;', name: 'Greek small letter iota with dialytika and tonos', characterSet: 'WGL4' },
  { character: '&#913;', decimalCode: '&amp;#913;', name: 'Greek capital letter alpha', characterSet: '' },
  { character: '&#914;', decimalCode: '&amp;#914;', name: 'Greek capital letter beta', characterSet: '' },
  { character: '&#915;', decimalCode: '&amp;#915;', name: 'Greek capital letter gamma', characterSet: '' },
  { character: '&#916;', decimalCode: '&amp;#916;', name: 'Greek capital letter delta', characterSet: '' },
  { character: '&#917;', decimalCode: '&amp;#917;', name: 'Greek capital letter epsilon', characterSet: '' },
  { character: '&#918;', decimalCode: '&amp;#918;', name: 'Greek capital letter zeta', characterSet: '' },
  { character: '&#919;', decimalCode: '&amp;#919;', name: 'Greek capital letter eta', characterSet: '' },
  { character: '&#920;', decimalCode: '&amp;#920;', name: 'Greek capital letter theta', characterSet: '' },
  { character: '&#921;', decimalCode: '&amp;#921;', name: 'Greek capital letter iota', characterSet: '' },
  { character: '&#922;', decimalCode: '&amp;#922;', name: 'Greek capital letter kappa', characterSet: '' },
  { character: '&#923;', decimalCode: '&amp;#923;', name: 'Greek capital letter lamda', characterSet: '' },
  { character: '&#924;', decimalCode: '&amp;#924;', name: 'Greek capital letter mu', characterSet: '' },
  { character: '&#925;', decimalCode: '&amp;#925;', name: 'Greek capital letter nu', characterSet: '' },
  { character: '&#926;', decimalCode: '&amp;#926;', name: 'Greek capital letter xi', characterSet: '' },
  { character: '&#927;', decimalCode: '&amp;#927;', name: 'Greek capital letter omicron', characterSet: '' },
  { character: '&#928;', decimalCode: '&amp;#928;', name: 'Greek capital letter pi', characterSet: '' },
  { character: '&#929;', decimalCode: '&amp;#929;', name: 'Greek capital letter rho', characterSet: '' },
  { character: '&#931;', decimalCode: '&amp;#931;', name: 'Greek capital letter sigma', characterSet: '' },
  { character: '&#932;', decimalCode: '&amp;#932;', name: 'Greek capital letter tau', characterSet: '' },
  { character: '&#933;', decimalCode: '&amp;#933;', name: 'Greek capital letter upsilon', characterSet: '' },
  { character: '&#934;', decimalCode: '&amp;#934;', name: 'Greek capital letter phi', characterSet: '' },
  { character: '&#935;', decimalCode: '&amp;#935;', name: 'Greek capital letter chi', characterSet: '' },
  { character: '&#936;', decimalCode: '&amp;#936;', name: 'Greek capital letter psi', characterSet: '' },
  { character: '&#937;', decimalCode: '&amp;#937;', name: 'Greek capital letter omega', characterSet: '' },
  { character: '&#938;', decimalCode: '&amp;#938;', name: 'Greek capital letter iota with dialytika', characterSet: 'WGL4' },
  { character: '&#939;', decimalCode: '&amp;#939;', name: 'Greek capital letter upsilon with dialytika', characterSet: 'WGL4' },
  { character: '&#940;', decimalCode: '&amp;#940;', name: 'Greek small letter alpha with tonos', characterSet: 'WGL4' },
  { character: '&#941;', decimalCode: '&amp;#941;', name: 'Greek small letter epsilon with tonos', characterSet: 'WGL4' },
  { character: '&#942;', decimalCode: '&amp;#942;', name: 'Greek small letter eta with tonos', characterSet: 'WGL4' },
  { character: '&#943;', decimalCode: '&amp;#943;', name: 'Greek small letter iota with tonos', characterSet: 'WGL4' },
  { character: '&#944;', decimalCode: '&amp;#944;', name: 'Greek small letter upsilon with dialytika and tonos', characterSet: 'WGL4' },
  { character: '&#945;', decimalCode: '&amp;#945;', name: 'Greek small letter alpha', characterSet: '' },
  { character: '&#946;', decimalCode: '&amp;#946;', name: 'Greek small letter beta', characterSet: '' },
  { character: '&#947;', decimalCode: '&amp;#947;', name: 'Greek small letter gamma', characterSet: '' },
  { character: '&#948;', decimalCode: '&amp;#948;', name: 'Greek small letter delta', characterSet: '' },
  { character: '&#949;', decimalCode: '&amp;#949;', name: 'Greek small letter epsilon', characterSet: '' },
  { character: '&#950;', decimalCode: '&amp;#950;', name: 'Greek small letter zeta', characterSet: '' },
  { character: '&#951;', decimalCode: '&amp;#951;', name: 'Greek small letter eta', characterSet: '' },
  { character: '&#952;', decimalCode: '&amp;#952;', name: 'Greek small letter theta', characterSet: '' },
  { character: '&#953;', decimalCode: '&amp;#953;', name: 'Greek small letter iota', characterSet: '' },
  { character: '&#954;', decimalCode: '&amp;#954;', name: 'Greek small letter kappa', characterSet: '' },
  { character: '&#955;', decimalCode: '&amp;#955;', name: 'Greek small letter lamda', characterSet: '' },
  { character: '&#956;', decimalCode: '&amp;#956;', name: 'Greek small letter mu', characterSet: '' },
  { character: '&#957;', decimalCode: '&amp;#957;', name: 'Greek small letter nu', characterSet: '' },
  { character: '&#958;', decimalCode: '&amp;#958;', name: 'Greek small letter xi', characterSet: '' },
  { character: '&#959;', decimalCode: '&amp;#959;', name: 'Greek small letter omicron', characterSet: '' },
  { character: '&#960;', decimalCode: '&amp;#960;', name: 'Greek small letter pi', characterSet: '' },
  { character: '&#961;', decimalCode: '&amp;#961;', name: 'Greek small letter rho', characterSet: '' },
  { character: '&#962;', decimalCode: '&amp;#962;', name: 'Greek small letter final sigma', characterSet: '' },
  { character: '&#963;', decimalCode: '&amp;#963;', name: 'Greek small letter sigma', characterSet: '' },
  { character: '&#964;', decimalCode: '&amp;#964;', name: 'Greek small letter tau', characterSet: '' },
  { character: '&#965;', decimalCode: '&amp;#965;', name: 'Greek small letter upsilon', characterSet: '' },
  { character: '&#966;', decimalCode: '&amp;#966;', name: 'Greek small letter phi', characterSet: '' },
  { character: '&#967;', decimalCode: '&amp;#967;', name: 'Greek small letter chi', characterSet: '' },
  { character: '&#968;', decimalCode: '&amp;#968;', name: 'Greek small letter psi', characterSet: '' },
  { character: '&#969;', decimalCode: '&amp;#969;', name: 'Greek small letter omega', characterSet: '' },
  { character: '&#970;', decimalCode: '&amp;#970;', name: 'Greek small letter iota with dialytika', characterSet: 'WGL4' },
  { character: '&#971;', decimalCode: '&amp;#971;', name: 'Greek small letter upsilon with dialytika', characterSet: 'WGL4' },
  { character: '&#972;', decimalCode: '&amp;#972;', name: 'Greek small letter omicron with tonos', characterSet: 'WGL4' },
  { character: '&#973;', decimalCode: '&amp;#973;', name: 'Greek small letter upsilon with tonos', characterSet: 'WGL4' },
  { character: '&#974;', decimalCode: '&amp;#974;', name: 'Greek small letter omega with tonos', characterSet: 'WGL4' },
  { character: '&#977;', decimalCode: '&amp;#977;', name: 'Greek theta symbol', characterSet: '' },
  { character: '&#978;', decimalCode: '&amp;#978;', name: 'Greek upsilon with hook symbol', characterSet: '' },
  { character: '&#981;', decimalCode: '&amp;#981;', name: 'Greek phi symbol', characterSet: '' },
  { character: '&#982;', decimalCode: '&amp;#982;', name: 'Greek pi symbol', characterSet: '' },
  { character: '&#1025;', decimalCode: '&amp;#1025;', name: 'Cyrillic capital letter io', characterSet: 'WGL4' },
  { character: '&#1026;', decimalCode: '&amp;#1026;', name: 'Cyrillic capital letter dje', characterSet: 'WGL4' },
  { character: '&#1027;', decimalCode: '&amp;#1027;', name: 'Cyrillic capital letter gje', characterSet: 'WGL4' },
  { character: '&#1028;', decimalCode: '&amp;#1028;', name: 'Cyrillic capital letter ukrainian ie', characterSet: 'WGL4' },
  { character: '&#1029;', decimalCode: '&amp;#1029;', name: 'Cyrillic capital letter dze', characterSet: 'WGL4' },
  { character: '&#1030;', decimalCode: '&amp;#1030;', name: 'Cyrillic capital letter byelorussian-ukrainian i', characterSet: 'WGL4' },
  { character: '&#1031;', decimalCode: '&amp;#1031;', name: 'Cyrillic capital letter yi', characterSet: 'WGL4' },
  { character: '&#1032;', decimalCode: '&amp;#1032;', name: 'Cyrillic capital letter je', characterSet: 'WGL4' },
  { character: '&#1033;', decimalCode: '&amp;#1033;', name: 'Cyrillic capital letter lje', characterSet: 'WGL4' },
  { character: '&#1034;', decimalCode: '&amp;#1034;', name: 'Cyrillic capital letter nje', characterSet: 'WGL4' },
  { character: '&#1035;', decimalCode: '&amp;#1035;', name: 'Cyrillic capital letter tshe', characterSet: 'WGL4' },
  { character: '&#1036;', decimalCode: '&amp;#1036;', name: 'Cyrillic capital letter kje', characterSet: 'WGL4' },
  { character: '&#1038;', decimalCode: '&amp;#1038;', name: 'Cyrillic capital letter short u', characterSet: 'WGL4' },
  { character: '&#1039;', decimalCode: '&amp;#1039;', name: 'Cyrillic capital letter dzhe', characterSet: 'WGL4' },
  { character: '&#1040;', decimalCode: '&amp;#1040;', name: 'Cyrillic capital letter a', characterSet: 'WGL4' },
  { character: '&#1041;', decimalCode: '&amp;#1041;', name: 'Cyrillic capital letter be', characterSet: 'WGL4' },
  { character: '&#1042;', decimalCode: '&amp;#1042;', name: 'Cyrillic capital letter ve', characterSet: 'WGL4' },
  { character: '&#1043;', decimalCode: '&amp;#1043;', name: 'Cyrillic capital letter ghe', characterSet: 'WGL4' },
  { character: '&#1044;', decimalCode: '&amp;#1044;', name: 'Cyrillic capital letter de', characterSet: 'WGL4' },
  { character: '&#1045;', decimalCode: '&amp;#1045;', name: 'Cyrillic capital letter ie', characterSet: 'WGL4' },
  { character: '&#1046;', decimalCode: '&amp;#1046;', name: 'Cyrillic capital letter zhe', characterSet: 'WGL4' },
  { character: '&#1047;', decimalCode: '&amp;#1047;', name: 'Cyrillic capital letter ze', characterSet: 'WGL4' },
  { character: '&#1048;', decimalCode: '&amp;#1048;', name: 'Cyrillic capital letter i', characterSet: 'WGL4' },
  { character: '&#1049;', decimalCode: '&amp;#1049;', name: 'Cyrillic capital letter short i', characterSet: 'WGL4' },
  { character: '&#1050;', decimalCode: '&amp;#1050;', name: 'Cyrillic capital letter ka', characterSet: 'WGL4' },
  { character: '&#1051;', decimalCode: '&amp;#1051;', name: 'Cyrillic capital letter el', characterSet: 'WGL4' },
  { character: '&#1052;', decimalCode: '&amp;#1052;', name: 'Cyrillic capital letter em', characterSet: 'WGL4' },
  { character: '&#1053;', decimalCode: '&amp;#1053;', name: 'Cyrillic capital letter en', characterSet: 'WGL4' },
  { character: '&#1054;', decimalCode: '&amp;#1054;', name: 'Cyrillic capital letter o', characterSet: 'WGL4' },
  { character: '&#1055;', decimalCode: '&amp;#1055;', name: 'Cyrillic capital letter pe', characterSet: 'WGL4' },
  { character: '&#1056;', decimalCode: '&amp;#1056;', name: 'Cyrillic capital letter er', characterSet: 'WGL4' },
  { character: '&#1057;', decimalCode: '&amp;#1057;', name: 'Cyrillic capital letter es', characterSet: 'WGL4' },
  { character: '&#1058;', decimalCode: '&amp;#1058;', name: 'Cyrillic capital letter te', characterSet: 'WGL4' },
  { character: '&#1059;', decimalCode: '&amp;#1059;', name: 'Cyrillic capital letter u', characterSet: 'WGL4' },
  { character: '&#1060;', decimalCode: '&amp;#1060;', name: 'Cyrillic capital letter ef', characterSet: 'WGL4' },
  { character: '&#1061;', decimalCode: '&amp;#1061;', name: 'Cyrillic capital letter ha', characterSet: 'WGL4' },
  { character: '&#1062;', decimalCode: '&amp;#1062;', name: 'Cyrillic capital letter tse', characterSet: 'WGL4' },
  { character: '&#1063;', decimalCode: '&amp;#1063;', name: 'Cyrillic capital letter che', characterSet: 'WGL4' },
  { character: '&#1064;', decimalCode: '&amp;#1064;', name: 'Cyrillic capital letter sha', characterSet: 'WGL4' },
  { character: '&#1065;', decimalCode: '&amp;#1065;', name: 'Cyrillic capital letter shcha', characterSet: 'WGL4' },
  { character: '&#1066;', decimalCode: '&amp;#1066;', name: 'Cyrillic capital letter hard sign', characterSet: 'WGL4' },
  { character: '&#1067;', decimalCode: '&amp;#1067;', name: 'Cyrillic capital letter yeru', characterSet: 'WGL4' },
  { character: '&#1068;', decimalCode: '&amp;#1068;', name: 'Cyrillic capital letter soft sign', characterSet: 'WGL4' },
  { character: '&#1069;', decimalCode: '&amp;#1069;', name: 'Cyrillic capital letter e', characterSet: 'WGL4' },
  { character: '&#1070;', decimalCode: '&amp;#1070;', name: 'Cyrillic capital letter yu', characterSet: 'WGL4' },
  { character: '&#1071;', decimalCode: '&amp;#1071;', name: 'Cyrillic capital letter ya', characterSet: 'WGL4' },
  { character: '&#1072;', decimalCode: '&amp;#1072;', name: 'Cyrillic small letter a', characterSet: 'WGL4' },
  { character: '&#1073;', decimalCode: '&amp;#1073;', name: 'Cyrillic small letter be', characterSet: 'WGL4' },
  { character: '&#1074;', decimalCode: '&amp;#1074;', name: 'Cyrillic small letter ve', characterSet: 'WGL4' },
  { character: '&#1075;', decimalCode: '&amp;#1075;', name: 'Cyrillic small letter ghe', characterSet: 'WGL4' },
  { character: '&#1076;', decimalCode: '&amp;#1076;', name: 'Cyrillic small letter de', characterSet: 'WGL4' },
  { character: '&#1077;', decimalCode: '&amp;#1077;', name: 'Cyrillic small letter ie', characterSet: 'WGL4' },
  { character: '&#1078;', decimalCode: '&amp;#1078;', name: 'Cyrillic small letter zhe', characterSet: 'WGL4' },
  { character: '&#1079;', decimalCode: '&amp;#1079;', name: 'Cyrillic small letter ze', characterSet: 'WGL4' },
  { character: '&#1080;', decimalCode: '&amp;#1080;', name: 'Cyrillic small letter i', characterSet: 'WGL4' },
  { character: '&#1081;', decimalCode: '&amp;#1081;', name: 'Cyrillic small letter short i', characterSet: 'WGL4' },
  { character: '&#1082;', decimalCode: '&amp;#1082;', name: 'Cyrillic small letter ka', characterSet: 'WGL4' },
  { character: '&#1083;', decimalCode: '&amp;#1083;', name: 'Cyrillic small letter el', characterSet: 'WGL4' },
  { character: '&#1084;', decimalCode: '&amp;#1084;', name: 'Cyrillic small letter em', characterSet: 'WGL4' },
  { character: '&#1085;', decimalCode: '&amp;#1085;', name: 'Cyrillic small letter en', characterSet: 'WGL4' },
  { character: '&#1086;', decimalCode: '&amp;#1086;', name: 'Cyrillic small letter o', characterSet: 'WGL4' },
  { character: '&#1087;', decimalCode: '&amp;#1087;', name: 'Cyrillic small letter pe', characterSet: 'WGL4' },
  { character: '&#1088;', decimalCode: '&amp;#1088;', name: 'Cyrillic small letter er', characterSet: 'WGL4' },
  { character: '&#1089;', decimalCode: '&amp;#1089;', name: 'Cyrillic small letter es', characterSet: 'WGL4' },
  { character: '&#1090;', decimalCode: '&amp;#1090;', name: 'Cyrillic small letter te', characterSet: 'WGL4' },
  { character: '&#1091;', decimalCode: '&amp;#1091;', name: 'Cyrillic small letter u', characterSet: 'WGL4' },
  { character: '&#1092;', decimalCode: '&amp;#1092;', name: 'Cyrillic small letter ef', characterSet: 'WGL4' },
  { character: '&#1093;', decimalCode: '&amp;#1093;', name: 'Cyrillic small letter ha', characterSet: 'WGL4' },
  { character: '&#1094;', decimalCode: '&amp;#1094;', name: 'Cyrillic small letter tse', characterSet: 'WGL4' },
  { character: '&#1095;', decimalCode: '&amp;#1095;', name: 'Cyrillic small letter che', characterSet: 'WGL4' },
  { character: '&#1096;', decimalCode: '&amp;#1096;', name: 'Cyrillic small letter sha', characterSet: 'WGL4' },
  { character: '&#1097;', decimalCode: '&amp;#1097;', name: 'Cyrillic small letter shcha', characterSet: 'WGL4' },
  { character: '&#1098;', decimalCode: '&amp;#1098;', name: 'Cyrillic small letter hard sign', characterSet: 'WGL4' },
  { character: '&#1099;', decimalCode: '&amp;#1099;', name: 'Cyrillic small letter yeru', characterSet: 'WGL4' },
  { character: '&#1100;', decimalCode: '&amp;#1100;', name: 'Cyrillic small letter soft sign', characterSet: 'WGL4' },
  { character: '&#1101;', decimalCode: '&amp;#1101;', name: 'Cyrillic small letter e', characterSet: 'WGL4' },
  { character: '&#1102;', decimalCode: '&amp;#1102;', name: 'Cyrillic small letter yu', characterSet: 'WGL4' },
  { character: '&#1103;', decimalCode: '&amp;#1103;', name: 'Cyrillic small letter ya', characterSet: 'WGL4' },
  { character: '&#1105;', decimalCode: '&amp;#1105;', name: 'Cyrillic small letter io', characterSet: 'WGL4' },
  { character: '&#1106;', decimalCode: '&amp;#1106;', name: 'Cyrillic small letter dje', characterSet: 'WGL4' },
  { character: '&#1107;', decimalCode: '&amp;#1107;', name: 'Cyrillic small letter gje', characterSet: 'WGL4' },
  { character: '&#1108;', decimalCode: '&amp;#1108;', name: 'Cyrillic small letter ukrainian ie', characterSet: 'WGL4' },
  { character: '&#1109;', decimalCode: '&amp;#1109;', name: 'Cyrillic small letter dze', characterSet: 'WGL4' },
  { character: '&#1110;', decimalCode: '&amp;#1110;', name: 'Cyrillic small letter byelorussian-ukrainian i', characterSet: 'WGL4' },
  { character: '&#1111;', decimalCode: '&amp;#1111;', name: 'Cyrillic small letter yi', characterSet: 'WGL4' },
  { character: '&#1112;', decimalCode: '&amp;#1112;', name: 'Cyrillic small letter je', characterSet: 'WGL4' },
  { character: '&#1113;', decimalCode: '&amp;#1113;', name: 'Cyrillic small letter lje', characterSet: 'WGL4' },
  { character: '&#1114;', decimalCode: '&amp;#1114;', name: 'Cyrillic small letter nje', characterSet: 'WGL4' },
  { character: '&#1115;', decimalCode: '&amp;#1115;', name: 'Cyrillic small letter tshe', characterSet: 'WGL4' },
  { character: '&#1116;', decimalCode: '&amp;#1116;', name: 'Cyrillic small letter kje', characterSet: 'WGL4' },
  { character: '&#1118;', decimalCode: '&amp;#1118;', name: 'Cyrillic small letter short u', characterSet: 'WGL4' },
  { character: '&#1119;', decimalCode: '&amp;#1119;', name: 'Cyrillic small letter dzhe', characterSet: 'WGL4' },
  { character: '&#1168;', decimalCode: '&amp;#1168;', name: 'Cyrillic capital letter ghe with upturn', characterSet: 'WGL4' },
  { character: '&#1169;', decimalCode: '&amp;#1169;', name: 'Cyrillic small letter ghe with upturn', characterSet: 'WGL4' },
  { character: '&#7808;', decimalCode: '&amp;#7808;', name: 'Latin capital letter w with grave', characterSet: 'WGL4' },
  { character: '&#7809;', decimalCode: '&amp;#7809;', name: 'Latin small letter w with grave', characterSet: 'WGL4' },
  { character: '&#7810;', decimalCode: '&amp;#7810;', name: 'Latin capital letter w with acute', characterSet: 'WGL4' },
  { character: '&#7811;', decimalCode: '&amp;#7811;', name: 'Latin small letter w with acute', characterSet: 'WGL4' },
  { character: '&#7812;', decimalCode: '&amp;#7812;', name: 'Latin capital letter w with diaeresis', characterSet: 'WGL4' },
  { character: '&#7813;', decimalCode: '&amp;#7813;', name: 'Latin small letter w with diaeresis', characterSet: 'WGL4' },
  { character: '&#7922;', decimalCode: '&amp;#7922;', name: 'Latin capital letter y with grave', characterSet: 'WGL4' },
  { character: '&#7923;', decimalCode: '&amp;#7923;', name: 'Latin small letter y with grave', characterSet: 'WGL4' },
  { character: '&#8213;', decimalCode: '&amp;#8213;', name: 'Horizontal bar', characterSet: 'WGL4' },
  { character: '&#8215;', decimalCode: '&amp;#8215;', name: 'Double low line', characterSet: 'WGL4' },
  { character: '&#8219;', decimalCode: '&amp;#8219;', name: 'Single high-reversed-9 quotation mark', characterSet: 'WGL4' },
  { character: '&#8240;', decimalCode: '&amp;#8240;', name: 'Per mille sign', characterSet: 'WGL4' },
  { character: '&#8242;', decimalCode: '&amp;#8242;', name: 'Prime', characterSet: '' },
  { character: '&#8243;', decimalCode: '&amp;#8243;', name: 'Double prime', characterSet: '' },
  { character: '&#8249;', decimalCode: '&amp;#8249;', name: 'Single left-pointing angle quotation mark', characterSet: 'WGL4' },
  { character: '&#8250;', decimalCode: '&amp;#8250;', name: 'Single right-pointing angle quotation mark', characterSet: 'WGL4' },
  {
    character: '&#8251;', decimalCode: '&amp;#8251;', name: 'Reference mark', characterSet: 'Wingdings'
  },
  { character: '&#8252;', decimalCode: '&amp;#8252;', name: 'Double exclamation mark', characterSet: 'WGL4' },
  {
    character: '&#8253;', decimalCode: '&amp;#8253;', name: 'Interrobang', characterSet: 'Wingdings'
  },
  { character: '&#8254;', decimalCode: '&amp;#8254;', name: 'Overline', characterSet: 'WGL4' },
  {
    character: '&#8258;', decimalCode: '&amp;#8258;', name: 'Asterism', characterSet: 'Wingdings'
  },
  { character: '&#8260;', decimalCode: '&amp;#8260;', name: 'Fraction slash', characterSet: '' },
  { character: '&#8319;', decimalCode: '&amp;#8319;', name: 'Superscript latin small letter n', characterSet: 'WGL4' },
  { character: '&#8355;', decimalCode: '&amp;#8355;', name: 'French franc sign', characterSet: 'WGL4' },
  { character: '&#8356;', decimalCode: '&amp;#8356;', name: 'Lira sign', characterSet: 'WGL4' },
  { character: '&#8359;', decimalCode: '&amp;#8359;', name: 'Peseta sign', characterSet: 'WGL4' },
  { character: '&#8453;', decimalCode: '&amp;#8453;', name: 'Care of', characterSet: 'WGL4' },
  { character: '&#8465;', decimalCode: '&amp;#8465;', name: 'Black-letter capital i', characterSet: '' },
  { character: '&#8467;', decimalCode: '&amp;#8467;', name: 'Script small l', characterSet: 'WGL4' },
  { character: '&#8470;', decimalCode: '&amp;#8470;', name: 'Numero sign', characterSet: 'WGL4' },
  { character: '&#8472;', decimalCode: '&amp;#8472;', name: 'Script capital p', characterSet: '' },
  { character: '&#8476;', decimalCode: '&amp;#8476;', name: 'Black-letter capital r', characterSet: '' },
  { character: '&#8486;', decimalCode: '&amp;#8486;', name: 'Ohm sign', characterSet: 'WGL4' },
  { character: '&#8494;', decimalCode: '&amp;#8494;', name: 'Estimated symbol', characterSet: 'WGL4' },
  { character: '&#8501;', decimalCode: '&amp;#8501;', name: 'Alef symbol', characterSet: '' },
  { character: '&#8616;', decimalCode: '&amp;#8616;', name: 'Up down arrow with base', characterSet: 'WGL4' },
  { character: '&#8629;', decimalCode: '&amp;#8629;', name: 'Downwards arrow with corner leftwards', characterSet: '' },
  { character: '&#8656;', decimalCode: '&amp;#8656;', name: 'Leftwards double arrow', characterSet: '' },
  { character: '&#8657;', decimalCode: '&amp;#8657;', name: 'Upwards double arrow', characterSet: '' },
  { character: '&#8658;', decimalCode: '&amp;#8658;', name: 'Rightwards double arrow', characterSet: '' },
  { character: '&#8659;', decimalCode: '&amp;#8659;', name: 'Downwards double arrow', characterSet: '' },
  { character: '&#8660;', decimalCode: '&amp;#8660;', name: 'Left right double arrow', characterSet: '' },
  { character: '&#8678;', decimalCode: '&amp;#8678;', name: 'Leftwards white arrow', characterSet: '' },
  { character: '&#8679;', decimalCode: '&amp;#8679;', name: 'Upwards white arrow', characterSet: '' },
  { character: '&#8680;', decimalCode: '&amp;#8680;', name: 'Rightwards white arrow', characterSet: '' },
  { character: '&#8681;', decimalCode: '&amp;#8681;', name: 'Downwards white arrow', characterSet: '' },
  { character: '&#8691;', decimalCode: '&amp;#8691;', name: 'Up down white arrow', characterSet: 'Wingdings' },
  { character: '&#8704;', decimalCode: '&amp;#8704;', name: 'For all', characterSet: '' },
  { character: '&#8706;', decimalCode: '&amp;#8706;', name: 'Partial differential', characterSet: '' },
  { character: '&#8707;', decimalCode: '&amp;#8707;', name: 'There exists', characterSet: '' },
  { character: '&#8709;', decimalCode: '&amp;#8709;', name: 'Empty set', characterSet: '' },
  { character: '&#8710;', decimalCode: '&amp;#8710;', name: 'Increment', characterSet: 'Differences' },
  { character: '&#8711;', decimalCode: '&amp;#8711;', name: 'Nabla', characterSet: '' },
  { character: '&#8712;', decimalCode: '&amp;#8712;', name: 'Element of', characterSet: '' },
  { character: '&#8713;', decimalCode: '&amp;#8713;', name: 'Not an element of', characterSet: '' },
  { character: '&#8717;', decimalCode: '&amp;#8717;', name: 'Small contains as member', characterSet: '' },
  { character: '&#8719;', decimalCode: '&amp;#8719;', name: 'N-ary product', characterSet: '' },
  { character: '&#8721;', decimalCode: '&amp;#8721;', name: 'N-ary summation', characterSet: '' },
  { character: '&#8722;', decimalCode: '&amp;#8722;', name: 'Minus sign', characterSet: '' },
  { character: '&#8725;', decimalCode: '&amp;#8725;', name: 'Division slash', characterSet: 'WGL4' },
  { character: '&#8727;', decimalCode: '&amp;#8727;', name: 'Asterisk operator', characterSet: '' },
  { character: '&#8729;', decimalCode: '&amp;#8729;', name: 'Bullet operator', characterSet: '' },
  { character: '&#8730;', decimalCode: '&amp;#8730;', name: 'Square root', characterSet: '' },
  { character: '&#8733;', decimalCode: '&amp;#8733;', name: 'Proportional to', characterSet: '' },
  { character: '&#8734;', decimalCode: '&amp;#8734;', name: 'Infinity', characterSet: '' },
  { character: '&#8735;', decimalCode: '&amp;#8735;', name: 'Right angle', characterSet: 'WGL4' },
  { character: '&#8736;', decimalCode: '&amp;#8736;', name: 'Angle', characterSet: '' },
  { character: '&#8743;', decimalCode: '&amp;#8743;', name: 'Logical and', characterSet: '' },
  { character: '&#8744;', decimalCode: '&amp;#8744;', name: 'Logical or', characterSet: '' },
  { character: '&#8745;', decimalCode: '&amp;#8745;', name: 'Intersection', characterSet: '' },
  { character: '&#8746;', decimalCode: '&amp;#8746;', name: 'Union', characterSet: '' },
  { character: '&#8747;', decimalCode: '&amp;#8747;', name: 'Integral', characterSet: '' },
  { character: '&#8756;', decimalCode: '&amp;#8756;', name: 'Therefore', characterSet: '' },
  { character: '&#8764;', decimalCode: '&amp;#8764;', name: 'Tilde operator', characterSet: '' },
  { character: '&#8773;', decimalCode: '&amp;#8773;', name: 'Approximately equal to', characterSet: '' },
  { character: '&#8776;', decimalCode: '&amp;#8776;', name: 'Almost equal to', characterSet: '' },
  { character: '&#8800;', decimalCode: '&amp;#8800;', name: 'Not equal to', characterSet: '' },
  { character: '&#8801;', decimalCode: '&amp;#8801;', name: 'Identical to', characterSet: '' },
  { character: '&#8804;', decimalCode: '&amp;#8804;', name: 'Less-than or equal to', characterSet: '' },
  { character: '&#8805;', decimalCode: '&amp;#8805;', name: 'Greater-than or equal to', characterSet: '' },
  {
    character: '&#8805;', decimalCode: '&amp;8805;', name: 'Greater-than or equal to', characterSet: 'Macroman'
  },
  { character: '&#8834;', decimalCode: '&amp;#8834;', name: 'Subset of', characterSet: '' },
  { character: '&#8835;', decimalCode: '&amp;#8835;', name: 'Superset of', characterSet: '' },
  { character: '&#8836;', decimalCode: '&amp;#8836;', name: 'Not a subset of', characterSet: '' },
  { character: '&#8838;', decimalCode: '&amp;#8838;', name: 'Subset of or equal to', characterSet: '' },
  { character: '&#8839;', decimalCode: '&amp;#8839;', name: 'Superset of or equal to', characterSet: '' },
  { character: '&#8853;', decimalCode: '&amp;#8853;', name: 'Circled plus', characterSet: '' },
  { character: '&#8855;', decimalCode: '&amp;#8855;', name: 'Circled times', characterSet: '' },
  { character: '&#8869;', decimalCode: '&amp;#8869;', name: 'Up tack', characterSet: '' },
  { character: '&#8901;', decimalCode: '&amp;#8901;', name: 'Dot operator', characterSet: '' },
  { character: '&#8962;', decimalCode: '&amp;#8962;', name: 'House', characterSet: 'WGL4' },
  { character: '&#8976;', decimalCode: '&amp;#8976;', name: 'Reversed not sign', characterSet: 'WGL4' },
  { character: '&#8977;', decimalCode: '&amp;#8977;', name: 'Square lozenge', characterSet: '' },
  { character: '&#8980;', decimalCode: '&amp;#8980;', name: 'Sector', characterSet: 'Wingdings' },
  { character: '&#8982;', decimalCode: '&amp;#8982;', name: 'Position indicator', characterSet: '' },
  { character: '&#8984;', decimalCode: '&amp;#8984;', name: 'Place of interest sign', characterSet: '' },
  { character: '&#8992;', decimalCode: '&amp;#8992;', name: 'Top half integral', characterSet: '' },
  { character: '&#8993;', decimalCode: '&amp;#8993;', name: 'Bottom half integral', characterSet: '' },
  { character: '&#8998;', decimalCode: '&amp;#8998;', name: 'Erase to the right', characterSet: '' },
  { character: '&#8999;', decimalCode: '&amp;#8999;', name: 'X in a rectangle box', characterSet: '' },
  { character: '&#9001;', decimalCode: '&amp;#9001;', name: 'Left-pointing angle bracket', characterSet: '' },
  { character: '&#9002;', decimalCode: '&amp;#9002;', name: 'Right-pointing angle bracket', characterSet: '' },
  { character: '&#9003;', decimalCode: '&amp;#9003;', name: 'Erase to the left', characterSet: '' },
  { character: '&#9043;', decimalCode: '&amp;#9043;', name: 'Apl functional symbol quad up caret', characterSet: '' },
  { character: '&#9115;', decimalCode: '&amp;#9115;', name: 'Left parenthesis upper hook', characterSet: '' },
  { character: '&#9116;', decimalCode: '&amp;#9116;', name: 'Left parenthesis extension', characterSet: '' },
  { character: '&#9117;', decimalCode: '&amp;#9117;', name: 'Left parenthesis lower hook', characterSet: '' },
  { character: '&#9118;', decimalCode: '&amp;#9118;', name: 'Right parenthesis upper hook', characterSet: '' },
  { character: '&#9119;', decimalCode: '&amp;#9119;', name: 'Right parenthesis extension', characterSet: '' },
  { character: '&#9120;', decimalCode: '&amp;#9120;', name: 'Right parenthesis lower hook', characterSet: '' },
  { character: '&#9121;', decimalCode: '&amp;#9121;', name: 'Left square bracket upper corner', characterSet: '' },
  { character: '&#9122;', decimalCode: '&amp;#9122;', name: 'Left square bracket extension', characterSet: '' },
  { character: '&#9123;', decimalCode: '&amp;#9123;', name: 'Left square bracket lower corner', characterSet: '' },
  { character: '&#9124;', decimalCode: '&amp;#9124;', name: 'Right square bracket upper corner', characterSet: '' },
  { character: '&#9125;', decimalCode: '&amp;#9125;', name: 'Right square bracket extension', characterSet: '' },
  { character: '&#9126;', decimalCode: '&amp;#9126;', name: 'Right square bracket lower corner', characterSet: '' },
  { character: '&#9127;', decimalCode: '&amp;#9127;', name: 'Left curly bracket upper hook', characterSet: '' },
  { character: '&#9128;', decimalCode: '&amp;#9128;', name: 'Left curly bracket middle piece', characterSet: '' },
  { character: '&#9129;', decimalCode: '&amp;#9129;', name: 'Left curly bracket lower hook', characterSet: '' },
  { character: '&#9130;', decimalCode: '&amp;#9130;', name: 'Curly bracket extension', characterSet: '' },
  { character: '&#9131;', decimalCode: '&amp;#9131;', name: 'Right curly bracket upper hook', characterSet: '' },
  { character: '&#9132;', decimalCode: '&amp;#9132;', name: 'Right curly bracket middle piece', characterSet: '' },
  { character: '&#9133;', decimalCode: '&amp;#9133;', name: 'Right curly bracket lower hook', characterSet: '' },
  { character: '&#9134;', decimalCode: '&amp;#9134;', name: 'Integral extension', characterSet: '' },
  { character: '&#9135;', decimalCode: '&amp;#9135;', name: 'Horizontal line extension', characterSet: '' },
  { character: '&#9168;', decimalCode: '&amp;#9168;', name: 'Vertical line extension', characterSet: '' },
  { character: '&#9312;', decimalCode: '&amp;#9312;', name: 'Circled digit one', characterSet: '' },
  { character: '&#9313;', decimalCode: '&amp;#9313;', name: 'Circled digit two', characterSet: '' },
  { character: '&#9314;', decimalCode: '&amp;#9314;', name: 'Circled digit three', characterSet: '' },
  { character: '&#9315;', decimalCode: '&amp;#9315;', name: 'Circled digit four', characterSet: '' },
  { character: '&#9316;', decimalCode: '&amp;#9316;', name: 'Circled digit five', characterSet: '' },
  { character: '&#9317;', decimalCode: '&amp;#9317;', name: 'Circled digit six', characterSet: '' },
  { character: '&#9318;', decimalCode: '&amp;#9318;', name: 'Circled digit seven', characterSet: '' },
  { character: '&#9319;', decimalCode: '&amp;#9319;', name: 'Circled digit eight', characterSet: '' },
  { character: '&#9320;', decimalCode: '&amp;#9320;', name: 'Circled digit nine', characterSet: '' },
  { character: '&#9321;', decimalCode: '&amp;#9321;', name: 'Circled number ten', characterSet: '' },
  { character: '&#9450;', decimalCode: '&amp;#9450;', name: 'Circled digit zero', characterSet: '' },
  { character: '&#9472;', decimalCode: '&amp;#9472;', name: 'Box drawings light horizontal', characterSet: 'WGL4' },
  { character: '&#9474;', decimalCode: '&amp;#9474;', name: 'Box drawings light vertical', characterSet: 'WGL4' },
  { character: '&#9484;', decimalCode: '&amp;#9484;', name: 'Box drawings light down and right', characterSet: 'WGL4' },
  { character: '&#9488;', decimalCode: '&amp;#9488;', name: 'Box drawings light down and left', characterSet: 'WGL4' },
  { character: '&#9492;', decimalCode: '&amp;#9492;', name: 'Box drawings light up and right', characterSet: 'WGL4' },
  { character: '&#9496;', decimalCode: '&amp;#9496;', name: 'Box drawings light up and left', characterSet: 'WGL4' },
  { character: '&#9500;', decimalCode: '&amp;#9500;', name: 'Box drawings light vertical and right', characterSet: 'WGL4' },
  { character: '&#9508;', decimalCode: '&amp;#9508;', name: 'Box drawings light vertical and left', characterSet: 'WGL4' },
  { character: '&#9516;', decimalCode: '&amp;#9516;', name: 'Box drawings light down and horizontal', characterSet: 'WGL4' },
  { character: '&#9524;', decimalCode: '&amp;#9524;', name: 'Box drawings light up and horizontal', characterSet: 'WGL4' },
  { character: '&#9532;', decimalCode: '&amp;#9532;', name: 'Box drawings light vertical and horizontal', characterSet: 'WGL4' },
  { character: '&#9552;', decimalCode: '&amp;#9552;', name: 'Box drawings double horizontal', characterSet: 'WGL4' },
  { character: '&#9553;', decimalCode: '&amp;#9553;', name: 'Box drawings double vertical', characterSet: 'WGL4' },
  { character: '&#9554;', decimalCode: '&amp;#9554;', name: 'Box drawings down single and right double', characterSet: 'WGL4' },
  { character: '&#9555;', decimalCode: '&amp;#9555;', name: 'Box drawings down double and right single', characterSet: 'WGL4' },
  { character: '&#9556;', decimalCode: '&amp;#9556;', name: 'Box drawings double down and right', characterSet: 'WGL4' },
  { character: '&#9557;', decimalCode: '&amp;#9557;', name: 'Box drawings down single and left double', characterSet: 'WGL4' },
  { character: '&#9558;', decimalCode: '&amp;#9558;', name: 'Box drawings down double and left single', characterSet: 'WGL4' },
  { character: '&#9559;', decimalCode: '&amp;#9559;', name: 'Box drawings double down and left', characterSet: 'WGL4' },
  { character: '&#9560;', decimalCode: '&amp;#9560;', name: 'Box drawings up single and right double', characterSet: 'WGL4' },
  { character: '&#9561;', decimalCode: '&amp;#9561;', name: 'Box drawings up double and right single', characterSet: 'WGL4' },
  { character: '&#9562;', decimalCode: '&amp;#9562;', name: 'Box drawings double up and right', characterSet: 'WGL4' },
  { character: '&#9563;', decimalCode: '&amp;#9563;', name: 'Box drawings up single and left double', characterSet: 'WGL4' },
  { character: '&#9564;', decimalCode: '&amp;#9564;', name: 'Box drawings up double and left single', characterSet: 'WGL4' },
  { character: '&#9565;', decimalCode: '&amp;#9565;', name: 'Box drawings double up and left', characterSet: 'WGL4' },
  { character: '&#9566;', decimalCode: '&amp;#9566;', name: 'Box drawings vertical single and right double', characterSet: 'WGL4' },
  { character: '&#9567;', decimalCode: '&amp;#9567;', name: 'Box drawings vertical double and right single', characterSet: 'WGL4' },
  { character: '&#9568;', decimalCode: '&amp;#9568;', name: 'Box drawings double vertical and right', characterSet: 'WGL4' },
  { character: '&#9569;', decimalCode: '&amp;#9569;', name: 'Box drawings vertical single and left double', characterSet: 'WGL4' },
  { character: '&#9570;', decimalCode: '&amp;#9570;', name: 'Box drawings vertical double and left single', characterSet: 'WGL4' },
  { character: '&#9571;', decimalCode: '&amp;#9571;', name: 'Box drawings double vertical and left', characterSet: 'WGL4' },
  { character: '&#9572;', decimalCode: '&amp;#9572;', name: 'Box drawings down single and horizontal double', characterSet: 'WGL4' },
  { character: '&#9573;', decimalCode: '&amp;#9573;', name: 'Box drawings down double and horizontal single', characterSet: 'WGL4' },
  { character: '&#9574;', decimalCode: '&amp;#9574;', name: 'Box drawings double down and horizontal', characterSet: 'WGL4' },
  { character: '&#9575;', decimalCode: '&amp;#9575;', name: 'Box drawings up single and horizontal double', characterSet: 'WGL4' },
  { character: '&#9576;', decimalCode: '&amp;#9576;', name: 'Box drawings up double and horizontal single', characterSet: 'WGL4' },
  { character: '&#9577;', decimalCode: '&amp;#9577;', name: 'Box drawings double up and horizontal', characterSet: 'WGL4' },
  { character: '&#9578;', decimalCode: '&amp;#9578;', name: 'Box drawings vertical single and horizontal double', characterSet: 'WGL4' },
  { character: '&#9579;', decimalCode: '&amp;#9579;', name: 'Box drawings vertical double and horizontal single', characterSet: 'WGL4' },
  { character: '&#9580;', decimalCode: '&amp;#9580;', name: 'Box drawings double vertical and horizontal', characterSet: 'WGL4' },
  { character: '&#9600;', decimalCode: '&amp;#9600;', name: 'Upper half block', characterSet: 'WGL4' },
  { character: '&#9604;', decimalCode: '&amp;#9604;', name: 'Lower half block', characterSet: 'WGL4' },
  { character: '&#9608;', decimalCode: '&amp;#9608;', name: 'Full block', characterSet: 'WGL4' },
  { character: '&#9612;', decimalCode: '&amp;#9612;', name: 'Left half block', characterSet: 'WGL4' },
  { character: '&#9616;', decimalCode: '&amp;#9616;', name: 'Right half block', characterSet: 'WGL4' },
  { character: '&#9617;', decimalCode: '&amp;#9617;', name: 'Light shade', characterSet: 'WGL4' },
  { character: '&#9618;', decimalCode: '&amp;#9618;', name: 'Medium shade', characterSet: 'WGL4' },
  { character: '&#9619;', decimalCode: '&amp;#9619;', name: 'Dark shade', characterSet: 'WGL4' },
  { character: '&#9642;', decimalCode: '&amp;#9642;', name: 'Black small square', characterSet: '' },
  { character: '&#9643;', decimalCode: '&amp;#9643;', name: 'White small square', characterSet: 'WGL4' },
  { character: '&#9644;', decimalCode: '&amp;#9644;', name: 'Black rectangle', characterSet: 'WGL4' },
  { character: '&#9670;', decimalCode: '&amp;#9670;', name: 'Black diamond', characterSet: '' },
  {
    character: '&#9671;', decimalCode: '&amp;#9671;', name: 'White diamond', characterSet: 'Wingdings'
  },
  {
    character: '&#9672;', decimalCode: '&amp;#9672;', name: 'White diamond containing black small diamond', characterSet: 'Wingdings'
  },
  { character: '&#9673;', decimalCode: '&amp;#9673;', name: 'Fisheye', characterSet: '' },
  { character: '&#9674;', decimalCode: '&amp;#9674;', name: 'Lozenge', characterSet: '' },
  { character: '&#9675;', decimalCode: '&amp;#9675;', name: 'White circle', characterSet: '' },
  { character: '&#9678;', decimalCode: '&amp;#9678;', name: 'Bullseye', characterSet: '' },
  {
    character: '&#9686;', decimalCode: '&amp;#9686;', name: 'Left half black circle', characterSet: 'Wingdings'
  },
  {
    character: '&#9687;', decimalCode: '&amp;#9687;', name: 'Right half black circle', characterSet: 'Wingdings'
  },
  { character: '&#9688;', decimalCode: '&amp;#9688;', name: 'Inverse bullet', characterSet: 'WGL4' },
  { character: '&#9689;', decimalCode: '&amp;#9689;', name: 'Inverse white circle', characterSet: 'WGL4' },
  {
    character: '&#9700;', decimalCode: '&amp;#9700;', name: '', characterSet: ''
  },
  {
    character: '&#9701;', decimalCode: '&amp;#9701;', name: '', characterSet: ''
  },
  { character: '&#9702;', decimalCode: '&amp;#9702;', name: 'White bullet', characterSet: 'WGL4' },
  {
    character: '&#9703;', decimalCode: '&amp;#9703;', name: '', characterSet: ''
  },
  {
    character: '&#9704;', decimalCode: '&amp;#9704;', name: '', characterSet: ''
  },
  {
    character: '&#9705;', decimalCode: '&amp;#9705;', name: '', characterSet: ''
  },
  {
    character: '&#9706;', decimalCode: '&amp;#9706;', name: '', characterSet: ''
  },
  {
    character: '&#9707;', decimalCode: '&amp;#9707;', name: '', characterSet: ''
  },
  {
    character: '&#9708;', decimalCode: '&amp;#9708;', name: '', characterSet: ''
  },
  {
    character: '&#9709;', decimalCode: '&amp;#9709;', name: '', characterSet: ''
  },
  {
    character: '&#9710;', decimalCode: '&amp;#9710;', name: '', characterSet: ''
  },
  {
    character: '&#9711;', decimalCode: '&amp;#9711;', name: '', characterSet: ''
  },
  { character: '&#9712;', decimalCode: '&amp;#9712;', name: '', characterSet: '' },
  { character: '&#9713;', decimalCode: '&amp;#9713;', name: '', characterSet: '' },
  { character: '&#9714;', decimalCode: '&amp;#9714;', name: '', characterSet: '' },
  { character: '&#9715;', decimalCode: '&amp;#9715;', name: '', characterSet: '' },
  { character: '&#9716;', decimalCode: '&amp;#9716;', name: '', characterSet: '' },
  { character: '&#9717;', decimalCode: '&amp;#9717;', name: '', characterSet: '' },
  { character: '&#9718;', decimalCode: '&amp;#9718;', name: '', characterSet: '' },
  { character: '&#9719;', decimalCode: '&amp;#9719;', name: '', characterSet: '' },
  { character: '&#9721;', decimalCode: '&amp;#9721;', name: '', characterSet: '' },
  { character: '&#9722;', decimalCode: '&amp;#9722;', name: '', characterSet: '' },
  { character: '&#9723;', decimalCode: '&amp;#9723;', name: 'White medium square', characterSet: 'Wingdings' },
  { character: '&#9724;', decimalCode: '&amp;#9724;', name: 'Black medium square', characterSet: 'Wingdings' },
  { character: '&#9725;', decimalCode: '&amp;#9725;', name: '', characterSet: '' },
  { character: '&#9726;', decimalCode: '&amp;#9726;', name: 'Black medium small square', characterSet: 'Wingdings' },
  { character: '&#9727;', decimalCode: '&amp;#9727;', name: '', characterSet: '' },
  {
    character: '&#9728;', decimalCode: '&amp;#9728;', name: '', characterSet: ''
  },
  {
    character: '&#9729;', decimalCode: '&amp;#9729;', name: '', characterSet: ''
  },
  {
    character: '&#9730;', decimalCode: '&amp;#9730;', name: '', characterSet: ''
  },
  {
    character: '&#9731;', decimalCode: '&amp;#9731;', name: '', characterSet: ''
  },
  {
    character: '&#9732;', decimalCode: '&amp;#9732;', name: '', characterSet: ''
  },
  { character: '&#9733;', decimalCode: '&amp;#9733;', name: 'Black star', characterSet: '' },
  {
    character: '&#9734;', decimalCode: '&amp;#9734;', name: '', characterSet: ''
  },
  {
    character: '&#9735;', decimalCode: '&amp;#9735;', name: '', characterSet: ''
  },
  {
    character: '&#9736;', decimalCode: '&amp;#9736;', name: '', characterSet: ''
  },
  {
    character: '&#9737;', decimalCode: '&amp;#9737;', name: 'Sun', characterSet: 'Wingdings'
  },
  {
    character: '&#9738;', decimalCode: '&amp;#9738;', name: '', characterSet: ''
  },
  {
    character: '&#9739;', decimalCode: '&amp;#9739;', name: '', characterSet: ''
  },
  {
    character: '&#9740;', decimalCode: '&amp;#9740;', name: '', characterSet: ''
  },
  {
    character: '&#9741;', decimalCode: '&amp;#9741;', name: '', characterSet: ''
  },
  { character: '&#9742;', decimalCode: '&amp;#9742;', name: 'Black telephone', characterSet: '' },
  {
    character: '&#9743;', decimalCode: '&amp;#9743;', name: 'White telephone', characterSet: 'Wingdings'
  },
  {
    character: '&#9747;', decimalCode: '&amp;#9747;', name: 'Saltire', characterSet: 'Wingdings'
  },
  { character: '&#9748;', decimalCode: '&amp;#9748;', name: '', characterSet: '' },
  { character: '&#9749;', decimalCode: '&amp;#9749;', name: '', characterSet: '' },
  {
    character: '&#9750;', decimalCode: '&amp;#9750;', name: '', characterSet: ''
  },
  {
    character: '&#9751;', decimalCode: '&amp;#9751;', name: '', characterSet: ''
  },
  { character: '&#9752;', decimalCode: '&amp;#9752;', name: '', characterSet: '' },
  { character: '&#9753;', decimalCode: '&amp;#9753;', name: '', characterSet: '' },
  {
    character: '&#9754;', decimalCode: '&amp;#9754;', name: 'Black left pointing index', characterSet: 'Wingdings'
  },
  {
    character: '&#9755;', decimalCode: '&amp;#9755;', name: 'Black right pointing index', characterSet: 'Wingdings'
  },
  { character: '&#9756;', decimalCode: '&amp;#9756;', name: 'White left pointing index', characterSet: '' },
  { character: '&#9757;', decimalCode: '&amp;#9757;', name: 'White up pointing index', characterSet: '' },
  { character: '&#9758;', decimalCode: '&amp;#9758;', name: 'White right pointing index', characterSet: '' },
  { character: '&#9759;', decimalCode: '&amp;#9759;', name: 'White down pointing index', characterSet: '' },
  {
    character: '&#9760;', decimalCode: '&amp;#9760;', name: '', characterSet: ''
  },
  {
    character: '&#9774;', decimalCode: '&amp;#9774;', name: 'Peace Symbol', characterSet: ''
  },
  {
    character: '&#9775;', decimalCode: '&amp;#9775;', name: 'Yin Yang', characterSet: ''
  },
  { character: '&#9786;', decimalCode: '&amp;#9786;', name: 'White smiling face', characterSet: 'WGL4' },
  { character: '&#9787;', decimalCode: '&amp;#9787;', name: 'Black smiling face', characterSet: 'WGL4' },
  { character: '&#9788;', decimalCode: '&amp;#9788;', name: 'White sun with rays', characterSet: '' },
  {
    character: '&#9789;', decimalCode: '&amp;#9789;', name: 'First quarter moon', characterSet: 'Wingdings'
  },
  {
    character: '&#9790;', decimalCode: '&amp;#9790;', name: 'Last quarter moon', characterSet: 'Wingdings'
  },
  { character: '&#9792;', decimalCode: '&amp;#9792;', name: 'Female sign', characterSet: 'WGL4' },
  { character: '&#9794;', decimalCode: '&amp;#9794;', name: 'Male sign', characterSet: 'WGL4' },
  { character: '&#9824;', decimalCode: '&amp;#9824;', name: 'Black spade suit', characterSet: '' },
  { character: '&#9827;', decimalCode: '&amp;#9827;', name: 'Black club suit', characterSet: '' },
  { character: '&#9829;', decimalCode: '&amp;#9829;', name: 'Black heart suit', characterSet: '' },
  { character: '&#9830;', decimalCode: '&amp;#9830;', name: 'Black diamond suit', characterSet: '' },
  { character: '&#9834;', decimalCode: '&amp;#9834;', name: 'Eighth note', characterSet: 'WGL4' },
  { character: '&#9835;', decimalCode: '&amp;#9835;', name: 'Beamed eighth notes', characterSet: 'WGL4' },
  {
    character: '&#9851;', decimalCode: '&amp;#9851;', name: 'Black Universal Recycling Symbol', characterSet: ''
  },
  { character: '&#9899;', decimalCode: '&amp;#9899;', name: 'Medium black circle', characterSet: 'Wingdings' },
  {
    character: '&#9988;', decimalCode: '&amp;#9988;', name: 'White scissors', characterSet: 'Wingdings'
  },
  { character: '&#9990;', decimalCode: '&amp;#9990;', name: 'Telephone location sign', characterSet: '' },
  { character: '&#9993;', decimalCode: '&amp;#9993;', name: 'Envelope', characterSet: '' },
  { character: '&#9997;', decimalCode: '&amp;#9997;', name: 'Writing hand', characterSet: '' },
  {
    character: '&#10006;', decimalCode: '&amp;#10006;', name: 'Heavy multiplication x', characterSet: 'Wingdings'
  },
  { character: '&#10007;', decimalCode: '&amp;#10007;', name: 'Ballot x', characterSet: '' },
  {
    character: '&#10010;', decimalCode: '&amp;#10010;', name: 'Heavy greek cross', characterSet: 'Wingdings'
  },
  {
    character: '&#10013;', decimalCode: '&amp;#10013;', name: 'Latin cross', characterSet: 'Wingdings'
  },
  { character: '&#10022;', decimalCode: '&amp;#10022;', name: 'Black four pointed star', characterSet: '' },
  { character: '&#10026;', decimalCode: '&amp;#10026;', name: 'Circled white star', characterSet: '' },
  {
    character: '&#10031;', decimalCode: '&amp;#10031;', name: 'Pinwheel star', characterSet: 'Wingdings'
  },
  { character: '&#10032;', decimalCode: '&amp;#10032;', name: 'Shadowed white star', characterSet: '' },
  {
    character: '&#10033;', decimalCode: '&amp;#10033;', name: 'Heavy asterisk', characterSet: 'Wingdings'
  },
  { character: '&#10036;', decimalCode: '&amp;#10036;', name: 'Eight pointed black star', characterSet: '' },
  { character: '&#10037;', decimalCode: '&amp;#10037;', name: 'Eight pointed pinwheel star', characterSet: '' },
  { character: '&#10038;', decimalCode: '&amp;#10038;', name: 'Six pointed black star', characterSet: '' },
  {
    character: '&#10039;', decimalCode: '&amp;#10039;', name: 'Eight pointed rectilinear black star', characterSet: 'Wingdings'
  },
  { character: '&#10041;', decimalCode: '&amp;#10041;', name: 'Twelve pointed black star', characterSet: '' },
  { character: '&#10052;', decimalCode: '&amp;#10052;', name: 'Snowflake', characterSet: '' },
  { character: '&#10061;', decimalCode: '&amp;#10061;', name: 'Shadowed white circle', characterSet: '' },
  { character: '&#10065;', decimalCode: '&amp;#10065;', name: 'Lower right shadowed white square', characterSet: '' },
  { character: '&#10066;', decimalCode: '&amp;#10066;', name: 'Upper right shadowed white square', characterSet: '' },
  { character: '&#10070;', decimalCode: '&amp;#10070;', name: 'Black diamond minus white x', characterSet: '' },
  { character: '&#10077;', decimalCode: '&amp;#10077;', name: 'Heavy double turned comma quotation mark ornament', characterSet: '' },
  { character: '&#10078;', decimalCode: '&amp;#10078;', name: 'Heavy double comma quotation mark ornament', characterSet: '' },
  { character: '&#10102;', decimalCode: '&amp;#10102;', name: 'Dingbat negative circled digit one', characterSet: '' },
  { character: '&#10103;', decimalCode: '&amp;#10103;', name: 'Dingbat negative circled digit two', characterSet: '' },
  { character: '&#10104;', decimalCode: '&amp;#10104;', name: 'Dingbat negative circled digit three', characterSet: '' },
  { character: '&#10105;', decimalCode: '&amp;#10105;', name: 'Dingbat negative circled digit four', characterSet: '' },
  { character: '&#10106;', decimalCode: '&amp;#10106;', name: 'Dingbat negative circled digit five', characterSet: '' },
  { character: '&#10107;', decimalCode: '&amp;#10107;', name: 'Dingbat negative circled digit six', characterSet: '' },
  { character: '&#10108;', decimalCode: '&amp;#10108;', name: 'Dingbat negative circled digit seven', characterSet: '' },
  { character: '&#10109;', decimalCode: '&amp;#10109;', name: 'Dingbat negative circled digit eight', characterSet: '' },
  { character: '&#10110;', decimalCode: '&amp;#10110;', name: 'Dingbat negative circled digit nine', characterSet: '' },
  { character: '&#10111;', decimalCode: '&amp;#10111;', name: 'Dingbat negative circled number ten', characterSet: '' },
  { character: '&#10162;', decimalCode: '&amp;#10162;', name: 'Circled heavy white rightwards arrow', characterSet: '' },
  { character: '&#10209;', decimalCode: '&amp;#10209;', name: 'White concave-sided diamond', characterSet: 'Wingdings' },
  { character: '&#10680;', decimalCode: '&amp;#10680;', name: 'Circled reverse solidus', characterSet: 'Wingdings' },
  {
    character: '&#10687;', decimalCode: '&amp;#10687;', name: 'Circled bullet', characterSet: 'Wingdings'
  },
  { character: '&#10731;', decimalCode: '&amp;#10731;', name: 'Black lozenge', characterSet: 'Wingdings' },
  { character: '&#11035;', decimalCode: '&amp;#11035;', name: 'Black large square', characterSet: 'Wingdings' },
  { character: '&#11036;', decimalCode: '&amp;#11036;', name: 'White large square', characterSet: 'Wingdings' },
  { character: '&#11093;', decimalCode: '&amp;#11093;', name: 'Heavy large circle', characterSet: 'Wingdings' },
  { character: '&#63743;', decimalCode: '&amp;#63743;', name: 'Apple logo', characterSet: 'Macroman', characterSet: '' },
  { character: '&#64257;', decimalCode: '&amp;#64257;', name: 'Latin small ligature fi', characterSet: 'WGL4' },
  { character: '&#64258;', decimalCode: '&amp;#64258;', name: 'Latin small ligature fl', characterSet: 'WGL4' },
  { character: '&#127765;', decimalCode: '&amp;#127765;', name: 'Full moon symbol', characterSet: 'Wingdings' },
  { character: '&#128191;', decimalCode: '&amp;#128191;', name: 'Optical disc', characterSet: 'Wingdings' },
  { character: '&#128222;', decimalCode: '&amp;#128222;', name: 'Telephone receiver', characterSet: 'Wingdings' },
  { character: '&#128224;', decimalCode: '&amp;#128224;', name: 'Fax machine', characterSet: 'Wingdings' },
];